'use strict';

// 11. Sinif Mobil Uygulamalar Dersi - unitelendirilmis yillik plan icerigi.
// Kaynak: Karakopru GAP MTAL 2025-2026 yillik plani. Ogretmen panelden duzenleyebilir.

const M = 'Anlatım, araştırma, örnek olay, soru-cevap, uygulama, bireysel öğretim, beyin fırtınası';
const T = 'Etkileşimli tahta, bilgisayar, internet, mobil uygulama geliştirme yazılımı, cep telefonu, ders kitabı';

const r = (month, week, objectives, topic, notes) => ({
  month, week, hours: '5', objectives: objectives || '', topic: topic || '', methods: '', tools: '', notes: notes || ''
});
const banner = (text) => ({ banner: text });

const rows = [
  r('EYLÜL', '8-12 Eylül', 'İşletim sistemine uygun uygulama geliştirme ortamını kurar.',
    '1. MOBİL UYGULAMA GELİŞTİRMEYE HAZIRLIK\n1.1. TEMEL BİLEŞENLER\n1.1.1. Java Software Development Kit (JDK) Kurulumu\n1.1.2. Android Studio ve Software Development Kit (SDK) Kurulumu\n1.2. EMÜLATÖR KURULUMU\n1.3. TASARIM YAPILARI (ACTIVITY TEMPLATES)',
    '15 Temmuz Demokrasi ve Millî Birlik Günü'),
  r('EYLÜL', '15-19 Eylül', 'Uygulama geliştirirken farklı tasarım yapılarını kullanır.\nUygulama geliştirme ortamını kullanarak proje oluşturur.',
    '1.3.1. Activity\n1.3.2. Activity Çeşitleri\nDemokrasinin önemi'),
  r('EYLÜL', '22-26 Eylül', 'Yapılandırma bilgilerinin doğruluğuna dikkat ederek proje oluşturur.',
    '1.3.3. Activity Yaşam Döngüsü\n1.3.4. Activity Yaşam Döngüsü Metotları\n1.4. PROJE OLUŞTURMA'),
  r('EYLÜL', '29 Eylül-3 Ekim', 'Mobil uygulama ekran tasarımı yapar.',
    '1.4.1. Projenin Emülatörde Çalıştırılması\n1.4.2. Android Studio Tasarım Ekranı\n1.4.3. Ön İzleme Görünümünü Değiştirmek\n1.5. DOSYA VE DİZİN YAPILARI\n2. EKRAN TASARIMI'),
  r('EKİM', '6-10 Ekim', 'Görsel elemanları kullanarak arayüz tasarlar.',
    '2.1. MOBİL UYGULAMA EKRAN TASARIMINA GİRİŞ\n2.2. MOBİL UYGULAMA EKRAN YAPISI\n2.3. VIEW'),
  r('EKİM', '13-17 Ekim', 'Görsel elemanları kullanarak arayüz tasarlar.',
    '2.4. GÖRÜNÜM YERLEŞTİRME YÖNTEMLERİ\n2.4.1. Görünüm Yerleştirmek İçin XML Kullanımı\n2.4.2. Görünüm Yerleştirmek İçin Palette Kullanımı'),
  r('EKİM', '20-24 Ekim', 'Görsel elemanları kullanarak arayüz tasarlar.',
    '2.4.3. Görünüm Yerleştirmek İçin Java Kullanımı\n2.5. TEMEL GÖRÜNÜM SINIFLARI\n2.5.1. TextView\n2.5.2. EditText'),
  r('EKİM', '27-31 Ekim', 'Veri tipi isimlendirme kurallarına ve ihtiyaca uygun veri tipleri ve sabitleri kullanır.',
    '2.5.3. Button\n2.5.4. ImageView\n2.5.5. CheckBox\n2.5.6. ProgressBar',
    '29 Ekim Cumhuriyet Bayramı\n1.Sınav'),
  r('KASIM', '3-7 Kasım', 'Veri tipi isimlendirme kurallarına ve ihtiyaca uygun veri tipleri ve sabitleri kullanır.',
    '2.6. LAYOUT ÇEŞİTLERİ\n2.6.1. ConstraintLayout\n2.6.2. LinearLayout\n2.6.3. RelativeLayout\n2.6.4. FrameLayout\n3. TEMEL KOMUTLAR\n3.1. VERİ\n3.2. DEĞİŞKENLER\n3.2.1. Değişken Yapısı\n3.2.2. Değişken Tanımlama ve Atama\nAtatürk\'ün Cumhuriyetçilik İlkesi\n1.Dönem 1.Sınav\n3.3. VERİ TİPLERİ\n3.3.1. İlkel (Temel) Veri Tipleri\n3.3.2. Referans Veri Tipleri\n3.4. SABİTLER\nAtatürk\'ün eğitime ve bilime verdiği önem',
    '10 Kasım Atatürk\'ü Anma Günü ve Atatürk Haftası'),
  banner('ARA TATİL (10-14 KASIM)'),
  r('KASIM', '17-21 Kasım', 'İşlem önceliğini dikkate alarak operatörleri kullanır.',
    '3.5. İSİMLENDİRME KURALLARI\n3.6. OPERATÖRLER\n3.6.1. Aritmetik Operatörler'),
  r('KASIM', '24-28 Kasım', 'Hata ayıklama ve düzeltme yöntemlerini kullanır.',
    '3.6.2. Atama Operatörleri\n3.6.3. Karşılaştırma Operatörleri\n3.6.4. Mantıksal Operatörler'),
  r('ARALIK', '1-5 Aralık', 'Algoritmaya uygun karar kontrol yapılarını kullanır.',
    '3.7. HATA AYIKLAMA\n3.7.1. Logcat\n3.7.2. Durak Noktası'),
  r('ARALIK', '8-12 Aralık', 'Algoritmaya uygun karar kontrol yapılarını kullanır.',
    '3.7.3. Değişken İzleme (Watch)\n3.8. HATA DÜZELTME\n4. KARAR VE DÖNGÜ YAPILARI\n4.1. KARAR YAPILARI\n4.1.1. if Karar Yapısı\n4.1.2. if-else Karar Yapısı\n4.1.3. if-else-if Karar Yapısı\n4.1.4. Switch-Case Yapısı'),
  r('ARALIK', '15-19 Aralık', 'Algoritmaya uygun döngü kontrollerini kullanır.',
    '4.2. DÖNGÜ YAPILARI\n4.2.1. Sayaçlar\n4.2.2. for Döngüsü'),
  r('ARALIK', '22-26 Aralık', 'Algoritmaya uygun döngü kontrollerini kullanır.',
    '4.2.3. while Döngüsü\n4.2.4. do-while Döngüsü'),
  r('ARALIK', '29 Aralık-2 Ocak', 'Tekrarlanan kodları engellemek için metotlar ile çalışır.',
    '5. GELİŞMİŞ KOMUTLAR\n5.1. METOT\n5.1.1. Metot Yapısı\n5.1.2. Değer Döndürmeyen Metotlar\n1.Dönem 2.Sınav', '2.Sınav'),
  r('OCAK', '5-9 Ocak', 'Tekrarlanan kodları engellemek için metotlar ile çalışır.\nParametreleri doğru girerek hazır metotları kullanır.',
    '5.1.3. Değer Döndüren Metotlar\n5.1.4. Parametre Alan Metotlar\n5.1.5. Metotlarda Aşırı Yükleme'),
  r('OCAK', '12-16 Ocak', 'Algoritma yapısına ve kod okunabilirliğine uygun sınıflar ile çalışır.',
    '5.2. SINIF VE NESNE KAVRAMLARI\n5.2.1. Sınıf (Class)\n5.2.2. Nesne (Object) Oluşturma\n5.2.3. Sınıf Yapısı\n5.2.4. Erişim Belirleyiciler (Erişim Düzeyleri)\n5.2.5. Kurucu veya Yapıcı Metotlar (Constructors)'),
  banner('2025-2026 EĞİTİM-ÖĞRETİM YILI YARIYIL TATİLİ'),
  r('ŞUBAT', '2-6 Şubat', 'Algoritma yapısına ve kod okunabilirliğine uygun sınıflar ile çalışır.',
    '5.3. KAPSÜLLEME (ENCAPSULATION)\n5.3.1. Kapsülleme Yapısı\n5.3.2. Getter ve Setter Metotları'),
  r('ŞUBAT', '9-13 Şubat', 'Algoritma yapısına ve kod okunabilirliğine uygun sınıflar ile çalışır.',
    '5.4. KALITIM (INHERITANCE)\n5.5. ÇOKBİÇİMLİLİK (POLYMORPHISM)\n5.5.1. Çokbiçimlilik Yapısı'),
  r('ŞUBAT', '16-20 Şubat', 'İhtiyaca uygun dizileri tanımlar ve kullanır.',
    '5.6. DİZİLER\n5.6.1. Diziye Değer Atama\n5.6.2. ArrayList'),
  r('ŞUBAT', '23-27 Şubat', 'Gelişmiş uygulama tasarımı yapar.',
    '6. UYGULAMA TASARIMI\n6.1. PROJE YAPILANDIRMA AYARLARI\n6.1.1. AndroidManifest.xml Dosya Yapısı\n6.1.2. MainActivity\n6.1.3. res\n6.1.4. Gradle Scripts'),
  r('MART', '2-6 Mart', 'Gelişmiş uygulama tasarımı yapar.',
    '6.2. VIEW BINDING\n6.3. ACTIVITY YAPISI\n6.3.1. Activity Yaşam Döngüleri (Activity Life Cycle)\n6.3.2. Çoklu Aktiviteler'),
  r('MART', '9-13 Mart', 'Gelişmiş uygulama tasarımı yapar.',
    '6.4. ARAYÜZ TASARIMI\n6.5. FRAGMENT YAPISI\nAtatürk\'ün vatan ve millet sevgisi',
    '18 Mart Çanakkale Zaferi ve Şehitler Günü'),
  banner('ARA TATİL (16-20 MART)'),
  r('MART', '23-27 Mart', 'Mobil uygulama izin yapısını kullanır.', '', '1.Sınav'),
  r('MART', '30 Mart-3 Nisan', 'Uygulamadan elde edilen verileri veritabanına kaydeder.\nYerel veritabanı ile ilgili işlemleri yapar.',
    '6.6. MOBİL UYGULAMADA İZİNLER VE İZİN YAPISI\n6.6.1. İzin Tanımlamaları Yapısı\n6.6.2. İzin Onayları Almak\n7. VERİ TABANI İŞLEMLERİ\n7.1. SHAREDPREFERENCES KULLANIMI',
    '23 Nisan Ulusal Egemenlik ve Çocuk Bayramı'),
  r('NİSAN', '6-10 Nisan', 'Yerel veritabanı ile ilgili işlemleri yapar.',
    '7.2. YEREL VERİ TABANIYLA ÇALIŞMAK\n7.2.1. Sorgulama Komutları\n7.2.3. Mobil Uygulama Geliştirme Ortamında Yerel Veri Tabanı Kullanmak\n7.2.4. Mobil Uygulama Geliştirme Ortamında Kayıt Eklemek'),
  r('NİSAN', '13-17 Nisan', 'Uzak veritabanıyla çalışır.',
    '2.Dönem 1.Sınav\n7.2.5. Mobil Uygulama Geliştirme Ortamında Kayıt Silmek'),
  r('NİSAN', '20-24 Nisan', 'Uzak veritabanıyla çalışır.',
    '7.2.6. Mobil Uygulama Geliştirme Ortamında Kayıt Güncellemek\n7.2.7. Mobil Uygulama Geliştirme Ortamında Tüm Kayıtları Listelemek\n7.2.8. Özel Adaptör Kullanmak'),
  r('NİSAN', '27 Nisan-1 Mayıs', 'Yayın algılayıcılarıyla ilgili işlemleri yapar.\nSms ve ileti ile ilgili işlemleri yapar.',
    '7.2.9. Model Oluşturmak\n7.2.10. ArrayAdapter Sınıfıyla Özel Adaptör Oluşturmak\n7.3. UZAK VERİ TABANIYLA ÇALIŞMAK\n7.3.1. JSON Veri Düzeni\n7.3.2. Mobil Uygulama Geliştirme Ortamında Uzak Sunucu Yapılandırması'),
  r('MAYIS', '4-8 Mayıs', 'Bildirimlerle ilgili temel işlemleri yapar.\nFarklı uygulamalar ile etkileşime geçen uygulama tasarlar.',
    '7.3.3. Uzak Veri Tabanı Yönetimi\n7.3.4. Firestore Veri Tabanı Oluşturmak\n7.3.5. Uzak Veri Tabanında Yetkilendirme İşlemleri\n7.3.6. Mobil Uygulama Geliştirme Ortamında Uzak Veri Tabanıyla Çalışmak\n7.3.7. Mobil Uygulama Geliştirme Ortamında RecyclerView Nesnesiyle Çalışmak\n7.3.8. Uzak Veri Tabanından Veri Getirmek\n7.3.9. Mobil Uygulama Geliştirme Ortamında Uzak Veri Tabanına Veri Eklemek\n7.3.10. Uzak Veri Tabanından Veri Silmek\n7.3.11. Uzak Veri Tabanında Veri Güncellemek\n7.3.12. Firestore Veri Tabanında Kurallarla Çalışmak\nÇocuk, insan sevgisi ve evrensellik\n8.1. YAYIN ALGILAYICILARLA ÇALIŞMAK\n8.1.1. BroadcastReceiver Sınıfı Oluşturmak\n8.1.2. Kodla Yayın Algılayıcıları Tetiklemek\n8.2. SMS VE İLETİ GÖNDERMEK\n8.2.1. SMS Okumak\n8.2.2. İleti Göndermek\n8.3. BİLDİRİMLERLE ÇALIŞMAK\n8.3.1. Bildirimlerden Veri Almak\n8.4. BAŞKA UYGULAMALARLA ETKİLEŞİM KURMAK\n8.4.1. Paylaş Butonuyla Diğer Uygulamalardan Veri Almak\n8.4.2. BroadcastReceiver Kullanarak Uygulamaların Arasında Haberleşmek'),
  r('MAYIS', '11-15 Mayıs', 'Servislerle ilgili temel işlemleri yapar.',
    '8.5. SERVİSLERLE ÇALIŞMAK\n8.5.1. Arka Plan Servislerle Çalışmak\n8.5.2. Ön Plan Servislerle Çalışmak\n8.5.3. Sticky Servislerle Çalışmak'),
  r('MAYIS', '18-22 Mayıs', 'Workmanager ile zamanlanmış görev işlemlerini yapar.',
    '8.5.4. Bound Servislerle Çalışmak\n8.5.5. IntentServislerle Çalışmak\n8.6. WORKMANAGERLE ÇALIŞMAK\n8.6.1. Kısıtlamaları Tanımlamak\n8.6.2. Görevi Gecikmeli Başlatmak\n8.6.3. Zincirleme Çalışmak',
    '19 Mayıs Atatürk\'ü Anma, Gençlik ve Spor Bayramı'),
  r('MAYIS', '25-29 Mayıs', 'Sensörleri kullanarak uygulama geliştirme işlemini yapar.',
    '8.6.4. Görevleri İzlemek\n8.6.5. Görevlere Dışarıdan Veri Göndermek\nAtatürkçü düşüncede yer alan temel fikirler'),
  r('HAZİRAN', '1-5 Haziran', 'Uygulamayı güvenli hale getirerek paketleme işlemlerini yapar.',
    '8.7. SENSÖRLERLE ÇALIŞMAK\n8.7.1. Tüm Sensörlere Erişmek\n8.7.2. Sensör Olaylarıyla Çalışmak', '2.Sınav'),
  r('HAZİRAN', '8-12 Haziran', 'Uygulamayı markette yayınlar.',
    'ÖĞRENME BİRİMİ: UYGULAMA PAYLAŞIMI\n9. UYGULAMA YAYIMLAMA\n9.1. UYGULAMA MARKET GELİŞTİRİCİ AYARLARI\n2.Dönem 2.Sınav\n9.2. UYGULAMA YAYIMLAMA'),
  r('HAZİRAN', '15-19 Haziran', 'Uygulamayı markette yayınlar.', '9.2. UYGULAMA YAYIMLAMA'),
  r('HAZİRAN', '22-26 Haziran', 'Uygulamayı markette yayınlar.', 'Dönem Sonu Faaliyet Haftası Etkinlikleri')
];

module.exports = {
  name: '11. Sınıf Mobil Uygulamalar',
  area: 'Bilişim Teknolojileri Alanı',
  gradeLevel: '11.SINIF',
  courseName: 'Mobil Uygulamalar',
  weeklyHours: 5,
  defaultMethods: M,
  defaultTools: T,
  signTeachers: ['M. Fatih TAŞ', 'Gülsüm ÇELİK', 'İrfan BAYAT', 'M. Erhan MERMER', 'Ayhan AKKAYA', 'Adil ALTUN'],
  principalName: 'Hikmet ŞAHİN',
  rows
};
