'use strict';

// Bilisim Teknolojileri Alani derslerinin yillik plan icerikleri.
// Kaynak: Karakopru GAP MTAL 2025-2026 planlari. Tarihler 2026-2027 motoru ile
// otomatik hesaplanir; burada sadece icerik (kazanim/konu) sirasi tutulur.
// Yeni dersler bu diziye eklenir.

const SIGN = ['M. Fatih TAŞ', 'Gülsüm ÇELİK', 'İrfan BAYAT', 'M. Erhan MERMER', 'Ayhan AKKAYA', 'Adil ALTUN'];
const PRINCIPAL = 'Hikmet ŞAHİN';
const AREA = 'Bilişim Teknolojileri Alanı';

// Kisa yazim icin: r(saat, kazanim, [konu satirlari], not)
const r = (hours, objectives, topic, notes) => ({
  hours: String(hours),
  objectives: objectives || '',
  topic: Array.isArray(topic) ? topic.join('\n') : topic || '',
  notes: notes || ''
});

// ==================== PROGRAMLAMA TEMELLERİ (9. Sınıf) ====================
const programlamaTemelleri = {
  name: '9. Sınıf Programlama Temelleri',
  area: AREA,
  gradeLevel: '9.SINIF',
  courseName: 'Programlama Temelleri',
  weeklyHours: 4,
  defaultMethods: 'Anlatım, gösterip yaptırma, soru cevap, grup çalışması, beyin fırtınası, uygulama',
  defaultTools: 'Bilgisayar, akıllı tahta veya projeksiyon, internet bağlantısı, programlama dili, ders kitabı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(4, 'Problem çözme sürecindeki temel kavramları açıklar.',
      ['ÖĞRENME BİRİMİ 1: PROBLEM ÇÖZME VE ALGORİTMALAR', '1. PROBLEM ÇÖZME VE ALGORİTMALAR', '1.1. Problem Çözme ve Temel Kavramlar', '1.1.1. Problem']),
    r(4, 'Problem türlerini açıklar.\nVerilen problem için uygun teknikleri kullanarak çözüm bulur.',
      ['1.1.2. Problem Çözme Süreci', 'Demokrasinin önemi', '1.2. Problem Çözmede Temel İşlemler']),
    r(4, 'Verilen problemi çözmek üzere farklı algoritmalar tasarlar.\nAlgoritmanın hatalarını giderir.',
      ['1.2.1. Aritmetiksel Operatörler', '1.2.2. Karşılaştırma Operatörleri', '1.2.3. Mantıksal Operatörler', '1.2.4. İşlem Önceliği']),
    r(4, 'Verilen problemin çözümüne uygun akış şemaları oluşturur.',
      ['1.3. Algoritmalar', '1.3.1. Sözde Kod (Pseudo-code)', '1.3.2. Problem Çözmede Algoritma Hataları', '1.4. Akış Diyagramları']),
    r(4, 'Programlama dilinin özelliklerini ve diğer programlama dillerinden farklarını açıklar.',
      ['1.4.1. Flowcart (Akış Diyagramı) Hazırlama Programının Kurulumu', '1.4.2. Doğrusal Akış Şeması Örnekleri', '1.4.3. Karar İfadeleri Kullanılarak Hazırlanan Akış Şeması Örnekleri', '1.4.4. Döngüler Kullanılarak Hazırlanan Akış Şeması Örnekleri']),
    r(4, 'Programlama dilini bilgisayarına kurar.',
      ['ÖĞRENME BİRİMİ 3: PROGRAMLAMA DİLİ TEMELLERİ', '3. PROGRAMLAMA DİLİ TEMELLERİ', '3.1. Program ve Yazılım']),
    r(4, 'Programlama dilini kullanmak için gerekli araçları kurar.',
      ['3.2. Programlama Dili', '3.3. Neden Python?', '3.4. Python ile Neler Yapılabilir?']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['3.5. Python Kurulumu', '3.6. Python İçin Gerekli Araçlar', '3.6.1. Editör Kurulumu']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['3.6.2. Kütüphane Kullanımı', 'ÖĞRENME BİRİMİ 4: VERİ YAPILARI', '4. VERİ YAPILARI', '4.1. Değişken ve Sabit Kavramları', '4.1.1. Değişken Tanımlama', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav', '4.2. Operatörler', '4.2.1. Aritmetiksel Operatörler', '4.2.2. Atama Operatörleri', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['4.2.3. Karşılaştırma Operatörleri', '4.2.4. Mantıksal Operatörler']),
    r(4, 'Programlama dilinde veri tiplerini amacına uygun kullanır.',
      ['4.2.5. Kimlik Operatörleri', '4.3. Veri Tipleri', '4.3.1. String (Metinsel) Veri Tipi']),
    r(4, 'Programlama dilinde tanımladığı veriye ait temel fonksiyonların yer aldığı programları geliştirir.',
      ['4.3.2. Numbers (Sayısal) Veri Tipleri']),
    r(4, 'Farklı veri tiplerini (listeler, sözlükler vb.) kullanarak programlar geliştirir.',
      ['4.3.3. Listeler', '4.3.4. Tuple (Demet) Veri Tipi']),
    r(4, 'Farklı veri tiplerini (listeler, sözlükler vb.) kullanarak programlar geliştirir.',
      ['4.3.5. Dictionary (Sözlük) Veri Tipi', '4.3.6. Set (Küme) Veri Tipi']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['ÖĞRENME BİRİMİ 5: KARAR VE DÖNGÜ YAPILARI', '5. KARAR VE DÖNGÜ YAPILARI', '5.1. Karar Yapıları', '5.1.1. If-Else Yapısı']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['5.1.2. If-Elif-Else Yapısı', '1.Dönem 2.Sınav']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['5.1.3. İç İçe İfadeler']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.1. For Döngüsü']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.1.1. Range Kullanımı', '5.2.1.2. In Kullanımı']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.2. While Döngüsü']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.3. Break ve Continue Deyimleri']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['ÖĞRENME BİRİMİ 6: FONKSİYONLAR', '6. FONKSİYONLAR', '6.1. Fonksiyon', '6.1.1. Fonksiyonların Kullanımı']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.1.2. Gömülü Fonksiyonların ve Modüllerin Kullanımı', '6.2. Fonksiyon Tanımlama']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.2.1. Fonksiyon Düzenleme', '6.2.2. Parametre Kavramı ve Fonksiyonlar ile Parametre Kullanımı', '6.2.3. Değer Döndürme ve Return İfadesi', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.3. Lambda Fonksiyonlar']),
    r(4, 'Fonksiyon türlerine göre programlar geliştirir.',
      ['6.4. Özyinelemeli Fonksiyonlar', '6.4.1. Özyinelemeli Fonksiyonların Çalışma Şekli', '2.Dönem 1.Sınav']),
    r(4, 'Fonksiyon türlerine göre programlar geliştirir.',
      ['6.5. Fonksiyonlarda Kullanılan Değişkenlerin Kapsamı', 'ÖĞRENME BİRİMİ 7: TARİH VE STRİNG (METİN) İŞLEMLERİ', '7. TARİH VE METİN İŞLEMLERİ']),
    r(4, 'Tarih nesnesi oluşturur.\nTarih bilgisini biçimlendirir.',
      ['7.1. Tarih Nesnesi', '7.1.1. String (Metin) Olarak Girilen Değerlerin Tarih Bilgisinin Biçimlendirilmesi']),
    r(4, 'Metin bilgisini biçimlendirir.',
      ['7.2. String (Metin) İşlemleri', '7.2.1. String Verileri Birleştirme', '7.2.2. String Veri İçerisindeki Bir Karaktere Erişme', '7.2.3. String Verinin Uzunluğu']),
    r(4, 'Metin bilgisini biçimlendirir.',
      ['Çocuk, insan sevgisi ve evrensellik', '7.2.4. String Veriyi Parçalama (Slice) ve Bölme (Split)', '7.2.5. String Veri İçinde Karakter Değiştirme, Karakter Ekleme ve Çıkarma', '7.2.6. String Veri İçinde Bir Karakterin Yerini veya Metnin Karakteri İçerip İçermediğini Bulma']),
    r(4, 'İstisna işlemlerini açıklar.',
      ['7.2.7. String Veri İle Büyük ve Küçük Harf Değişimi Yapma', 'ÖĞRENME BİRİMİ 8: HATA YAKALAMA İŞLEMLERİ', '8. HATA YAKALAMA İŞLEMLERİ']),
    r(4, 'Try-except bloklarını kullanır.',
      ['8.1. Hata Kavramı ve Hata Türleri', '8.1.1. Hata Nedir?', '8.1.2. Hata Türleri']),
    r(4, 'Finally bloğunu kullanır.',
      ['8.2. Hata Yakalama', '8.3. Python Hata Türleri', '8.3.1. Birden Fazla (Except) Bloğu', '8.3.2. (as) İfadesi ile Orijinal Hata Mesajı Gösterme', '8.3.3. (finally) Bloğu', '8.3.4. (raise) İfadesi', '8.3.5. (assert) İfadesi', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(4, 'Programlama dilinde dosya okuma işlemlerini yapar.',
      ['ÖĞRENME BİRİMİ 9: DOSYA İŞLEMLERİ', '9. DOSYA İŞLEMLERİ', '9.1. Çalışma Dizini Ayarları ve Klasör Oluşturma', '9.1.1. Yol (Path) Tanımlama']),
    r(4, 'Dosya oluşturma ve yazma işlemlerini yapar.',
      ['9.1.2. Yolu Bilinen Klasör veya Dosyanın Var Olup Olmadığını Kontrol Etme', '9.1.3. Klasör Oluşturma', '9.1.4. Dosyalara Erişme ve Okuma']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['2.Dönem 2.Sınav', '9.2. Dosya Oluşturma ve Yazma']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['9.3. Dosya Silme ve Yedekleme']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== BİLİŞİM TEKNOLOJİLERİNİN TEMELLERİ (9. Sınıf) ====================
const bilisimTemelleri = {
  name: '9. Sınıf Bilişim Teknolojilerinin Temelleri',
  area: AREA,
  gradeLevel: '9.SINIF',
  courseName: 'Bilişim Teknolojilerinin Temelleri',
  weeklyHours: 3,
  defaultMethods: 'Anlatım, gösterip yaptırma, soru cevap, grup çalışması, beyin fırtınası, uygulama',
  defaultTools: "Bilgisayar, donanım birimleri, işletim sistemi kurulum cd'leri, el aletleri, ağ cihazları, çeşitli yazılımlar",
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(3, 'Bilişim teknolojilerini ve internet (genel ağ) ortamını kullanma ve yönetme sürecinde dikkat edilmesi gereken etik ilkeleri açıklar.',
      ['Öğrenme Birimi: BİLİŞİM ETİĞİ', '1. Bilişim Etiği', '1.1. Etik Ve Bilişim Etiği Kavramları', '1.1.1. Etik Ve Bilişim Etiği', '1.1.2. Bilişim Temel Hak Ve Özgürlükleri', '1.1.3. Kod Yazımında Etik İlkeler', '1.1.4. Sosyal Medya Etiği', '1.1.5. İnternet Etiği', 'Demokrasinin önemi']),
    r(3, 'Bilgi güvenliğinin önemini açıklar.\nBilgi güvenliğine yönelik tehditleri açıklar.',
      ['1.2. Bilgi Ve Bilgi Güvenliği', '1.3. Temel Güvenlik Prensipleri', '1.3.1. Bilgisayar Açılış Güvenliği', '1.3.2. Parola Güvenliği Prensipleri', '1.3.3. İnternet Erişim Güvenliği']),
    r(3, 'Kişisel bilgisayar ve ağ ortamında bilgi güvenliğini sağlamaya yönelik işlemleri yürütür.',
      ['1.3.4. E-Posta Güvenliği', '1.3.5. Sosyal Medyaya Erişim Güvenliği', '1.3.6. Dosya Erişim Ve Paylaşım Güvenliği', '1.3.7. Zararlı Yazılımlardan Korunma Prensipleri']),
    r(3, 'Fikri mülkiyet hakkını açıklar.',
      ['1.4. Fikrî Ve Sınai Mülkiyet', '1.4.1. Telif Hakkı', '1.4.2. Marka', '1.4.3. Patent', '1.4.4. Faydalı Model', '1.4.5. Tasarım', '1.4.6. Ticari Sır']),
    r(3, 'Birinci sanayi devrimini açıklar.\nİkinci sanayi devrimini açıklar.\nÜçüncü sanayi devrimini açıklar.',
      ['Öğrenme Birimi: DİJİTAL DÖNÜŞÜM', '2. Dijital Dönüşüm', '2.1. Birinci Sanayi Devrimi', '2.2. İkinci Sanayi Devrimi', '2.3. Üçüncü Sanayi Devrimi']),
    r(3, 'Dördüncü sanayi devrimini açıklar.\nDijital dönüşüm kavramlarını açıklar.\nBüyük veri teknolojilerini açıklar.',
      ['2.4. Dördüncü Sanayi Devrimi', '2.5. Dijital Dönüşüm Kavramları', '2.6. Büyük Veri Teknolojileri']),
    r(3, 'Arttırılmış gerçeklik ve sanallaştırmayı açıklar.\nSimülasyon sistemlerini açıklar.',
      ['2.7. Artırılmış Gerçeklik Ve Sanallaştırma', '2.8. Simülasyon Sistemleri', '2.8.1. Sanal Fabrika', '2.8.2. Dijital Fabrika', '2.8.3. Dijital İkiz']),
    r(3, 'Otomasyon ve sensör teknolojilerini açıklar.\nBulut bilişim sistemlerini açıklar.\nSiber güvenlik sistemlerini açıklar.',
      ['2.9. Otomasyon Ve Sensör Teknolojileri', '2.9.1. Sensörler', '2.9.2. Otomasyon Sistemlerinde Kullanılan Sensörler', '2.9.3. Akıllı Ev Sistemleri', '2.9.4. Akıllı Fabrikalar', '2.10. Bulut Bilişim Sistemleri', '2.11. Siber Güvenlik Sistemleri', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(3, 'Üretim ve hizmet süreçlerinde dijital izlenebilirlik sistemlerini (RFID, RTLS ilişkili teknolojiler) açıklar.\nAr-Ge projesi geliştirmeyi açıklar.',
      ['2.12. Üretim Ve Hizmet Süreçlerinde Dijital İzlenebilirlik Sistemleri', '2.12.1. RFID (Radio Frequency Identification)', '2.12.2. RTLS (Gerçek Zamanlı Yer Belirleme) Teknolojileri', '2.12.3. Beacon Teknolojileri', '2.13. Ar-Ge Projesi Geliştirme', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(3, 'Kullanım kılavuzuna uygun olarak anakartı montaj için hazırlar.',
      ['Öğrenme Birimi: İÇ DONANIM BİRİMLERİ', '3. İç Donanım Birimleri', '3.1. Anakartlar', '3.1.1. Statik Elektrik', '3.1.2. Bilgisayar Teknolojisinde Statik Elektrik', '3.1.3. Statik Elektriğin Önlenmesi']),
    r(3, 'Kullanım kılavuzuna uygun olarak anakartı montaj için hazırlar.',
      ['3.1.4. Anakart Ve Görevi', '3.1.5. Anakart Standartları', '3.1.6. Anakart Bileşenleri']),
    r(3, 'Bileşen uyumluluğuna göre anakarta işlemciyi monte eder.',
      ['3.2. İşlemciler', '3.2.1. İşlemci Yapısı', '3.2.2. İşlemcinin Çalışma Prensibi', '3.2.3. İşlemci Çeşitleri', '3.2.4. İşlemci Soğutması', '3.2.5. İşlemci Montajı']),
    r(3, 'Bellek birimlerini anakart üzerine doğru monte eder.',
      ['3.3. Bellekler', '3.3.1. Belleklerin Yapısı Ve Çalışması', '3.3.2. Bellek Çeşitleri', '3.3.3. Bellek Seçimi', '3.3.4. Bellek Montajı']),
    r(3, 'Genişleme yuvası kartlarını anakart üzerine doğru monte eder.',
      ['3.4. Genişleme Yuvası Kartları', '3.4.1. Ekran Kartı', '3.4.2. Ses Kartı', '3.4.3. Ethernet Kartı']),
    r(3, 'Disk sürücülerini kasaya doğru monte eder.',
      ['3.5. Disk Sürücüler', '3.5.1. Sabit Sürücüler', '3.5.2. Sabit Disk Sürücü Kabloları', '3.5.3. Sabit Disk Seçimi', '3.5.4. Sabit Disk Montajı', '3.6. Optik Sürücüler', '3.6.1. Cd Sürücüler', '3.6.2. Dvd Sürücüler', '3.6.3. Bluray Sürücüler']),
    r(3, 'Anakartı kasa içine monte eder.',
      ['3.7. Bilgisayar Kasasına Anakart Montajı', '3.7.1. Güç Kaynağı', '3.7.2. Ön Panel Konnektörleri', '3.7.3. Anakartın Kasa İçine Montajı', '1.Dönem 2.Sınav']),
    r(3, 'Giriş birimleri bağlantılarını yapar.',
      ['Öğrenme Birimi: DIŞ DONANIM BİRİMLERİ', '4. Dış Donanım Birimleri', '4.1. Giriş Birimleri', '4.1.1. Klavye', '4.1.2. Fare (Mouse)']),
    r(3, 'Görüntüleme birimlerinin bağlantısını yapar.',
      ['4.2. Görüntüleme Birimleri', '4.2.1. Monitörler', '4.2.2. Projeksiyon Cihazları']),
    r(3, 'Yazıcıların kablo bağlantılarını yapar.',
      ['4.3. Yazıcılar', '4.3.1. Yazıcı Temel Kavramları', '4.3.2. Yazıcı Çeşitleri', '4.3.3. Yazıcı Bağlantı Arabirimleri']),
    r(3, 'Görüntü işleme cihazlarının bağlantısını yapar.\nYönergelere uyarak sistemin ilk açılış ayarlarını yapar.',
      ['4.4. Görüntü İşleme Cihazları', '4.4.1. Tarayıcı (Scanner)', '4.4.2. Dijital Fotoğraf Makinesi', '4.4.3. Ağ Kameraları (Webcam)']),
    r(3, 'Kapalı kaynak kodlu işletim sistemi kurulumunu yapar.\nKapalı kaynak kodlu işletim sisteminde sürücülerin ve yardımcı yazılımların kurulumunu yapar.',
      ['4.4.4. Hafıza Kartları', '4.4.5. Kart Okuyucular', 'Öğrenme Birimi: İŞLETİM SİSTEMLERİ VE KURULUMLARI']),
    r(3, 'Açık kaynak kodlu işletim sistemi kurulumunu yapar.\nAçık kaynak kodlu işletim sisteminde sürücülerin ve yardımcı yazılımların kurulumunu yapar.',
      ['5. İşletim Sistemleri Ve Kurulum', '5.1. İşletim Sistemi Kurulum Öncesi Açılış Ayarları', '5.1.1. Bıos', '5.1.2. Post']),
    r(3, 'Donanım sorunlarını tespit ederek giderir.\nYazılım sorunlarını tespit ederek giderir.\nİşletim sistemi sorunlarını tespit ederek giderir.',
      ['5.1.3. Bıos Ayarları', '5.1.4. Bıos Uyarıları', '5.2. Kapalı Kaynak Kodlu İşletim Sistemi Kurulumu']),
    r(3, 'Kapalı kaynak kodlu işletim sistemi uygulama ayarlarını yapar.\nAçık kaynak kodlu işletim sistemi uygulama ayarlarını yapar.',
      ['5.2.1. Kurulum Öncesi Ayarlar', '5.2.2. Kapalı Kaynak İşletim Sistemi Kurulumu', '5.3. Kapalı Kaynak Kodlu İşletim Sisteminde Sürücülerin Ve Yardımcı Yazılımların Kurulumu', '5.3.1. İnternet Erişimi Sağlama']),
    r(3, '',
      ['5.3.2. İşletim Sistemini Etkinleştirme', '5.3.3. İşletim Sistemini Güncel Tutma', '5.3.4. Aygıt Sürücülerinin Yüklenmesi', '5.3.5. Aygıt Yöneticisi Ve İşlevleri']),
    r(3, '',
      ['5.3.6. Sürücülerin Elle Kurulması', '5.3.7. Yardımcı Yazılımların Kurulumu', '5.4. Açık Kaynak Kodlu İşletim Sistemi Kurulumu', '5.5. Açık Kaynak Kodlu İşletim Sisteminde Sürücülerin Ve Yardımcı Yazılımların Kurulumu']),
    r(3, '',
      ['5.5.1. İşletim Sistemini Güncelleme', '5.5.2. İnternet Erişimi Sağlama', '5.5.3. Aygıt Sürücülerinin Yüklenmesi', '5.5.4. Yardımcı Yazılımların Kurulumu']),
    r(3, '',
      ['5.5.5. Açık Kaynak Ofis Programı', 'Atatürk\'ün vatan ve millet sevgisi', '5.6. İşletim Sistemlerinde Donanım Sorunlarını Giderme', '5.7. İşletim Sisteminde Yazılım Sorunlarını Giderme', '5.8. İşletim Sisteminde Diğer Sorunlar', '2.Dönem 1.Sınav', 'Öğrenme Birimi: İŞLETİM SİSTEMLERİ TEMEL KULLANIMI', '6. İşletim Sistemleri Temel Kullanım', '6.1. İşletim Sistemi Uygulama Ayarları', '6.1.1. Kullanıcı Hesapları', '6.1.2. Görünüm Ve Kişiselleştirme Ayarları']),
    r(3, 'Kapalı kaynak kodlu işletim sisteminde güvenlik yazılımlarını kullanarak işletim sisteminin korunmasını sağlar.\nAçık kaynak kodlu işletim sisteminde güvenlik yazılımlarını kullanarak işletim sisteminin korunmasını sağlar.',
      ['6.1.3. Saat, Dil Ve Bölge Ayarları', '6.1.4. Güvenlik Ayarları', 'Çocuk, insan sevgisi ve evrensellik']),
    r(3, 'Açık ve kapalı kodlu işletim sistemlerinde web tarayıcılarını kullanır.\nFiziksel ortama göre ağ sisteminin fiziksel bağlantı tasarımını yapar.\nFiziksel ortama ve ağ çeşidine göre ağ topolojisini seçer.\nAğ çeşidi ve fiziksel ortama göre ağ cihazlarının fiziksel bağlantılarını yapar.',
      ['6.2. İşletim Sistemlerinde Web Tarayıcıları Kullanımı', '6.2.1. Kapalı Kaynak İşletim Sisteminde Web Tarayıcı Kurulumu', '6.2.2. Açık Kaynak İşletim Sisteminde Web Tarayıcı Kurulumu', 'Öğrenme Birimi: AĞ TEMELLERİ', '7. Ağ Temelleri']),
    r(3, 'Sistem güvenliği için iletim katmanı portlarını kullanır.\nTalimatlara göre uygulama katmanı uygulamalarını kullanır.\nAğ hizmetlerine göre ağ protokolünü yapılandırır.',
      ['7.1. Ağ Sistemleri', '7.1.1. Veri İletimi', '7.1.2. Veri İletim Yöntemleri']),
    r(3, 'Ağ cihazlarına doğru TCP/IP adres girişini yapar.\nAğı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['7.1.3. Ağ Çeşitleri', '7.1.4. Coğrafi Yapıya Göre Bilgisayar Ağları', '7.1.5. Fiziksel Topolojilere Göre Bilgisayar Ağları', '7.1.6. Organizasyon Yapısı']),
    r(3, '',
      ['7.2. Ağ Modeli', '7.2.1. Veri Haberleşmede Katman Kullanımı', '7.2.2. Osı Modeli', '7.2.3. Tcp / Ip Modeli', '7.2.4. İletişim Protokolleri', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(3, '',
      ['7.3. Ağ Cihazları Ve Ağ Kabloları', '7.3.1. Ağ Cihazları', '7.3.2. Ağ Kabloları']),
    r(3, '',
      ['7.4. Kablolama', '7.4.1. Kablo Hazırlama', '7.4.2. Yapısal Kablolama']),
    r(3, '',
      ['7.5. Ip Adresleme', '2.Dönem 2.Sınav', '7.5.1. Ipv4 (İnternet Protokol Versiyon 4)']),
    r(3, 'Ağı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['7.5.2. Ethernet Kartı']),
    r(3, 'Ağı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

module.exports = [programlamaTemelleri, bilisimTemelleri];
