'use strict';

// Bilisim Teknolojileri Alani derslerinin yillik plan icerikleri.
// Kaynak: Karakopru GAP MTAL 2025-2026 planlari. Tarihler 2026-2027 motoru ile
// otomatik hesaplanir; burada sadece icerik (kazanim/konu) sirasi tutulur.
// Yeni dersler bu diziye eklenir.

const SIGN = ['M. Fatih TAŞ', 'Gülsüm ÇELİK', 'İrfan BAYAT', 'M. Erhan MERMER', 'Ayhan AKKAYA', 'Adil ALTUN'];
const PRINCIPAL = 'Hikmet ŞAHİN';
const AREA = 'Bilişim Teknolojileri Alanı';

// Kisa yazim icin: r(saat, kazanim, [konu satirlari], not)
const r = (hours, objectives, topic, notes) => ({
  hours: String(hours),
  objectives: objectives || '',
  topic: Array.isArray(topic) ? topic.join('\n') : topic || '',
  notes: notes || ''
});

// ==================== PROGRAMLAMA TEMELLERİ (9. Sınıf) ====================
const programlamaTemelleri = {
  name: '9. Sınıf Programlama Temelleri',
  area: AREA,
  gradeLevel: '9.SINIF',
  courseName: 'Programlama Temelleri',
  weeklyHours: 4,
  defaultMethods: 'Anlatım, gösterip yaptırma, soru cevap, grup çalışması, beyin fırtınası, uygulama',
  defaultTools: 'Bilgisayar, akıllı tahta veya projeksiyon, internet bağlantısı, programlama dili, ders kitabı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(4, 'Problem çözme sürecindeki temel kavramları açıklar.',
      ['ÖĞRENME BİRİMİ 1: PROBLEM ÇÖZME VE ALGORİTMALAR', '1. PROBLEM ÇÖZME VE ALGORİTMALAR', '1.1. Problem Çözme ve Temel Kavramlar', '1.1.1. Problem']),
    r(4, 'Problem türlerini açıklar.\nVerilen problem için uygun teknikleri kullanarak çözüm bulur.',
      ['1.1.2. Problem Çözme Süreci', 'Demokrasinin önemi', '1.2. Problem Çözmede Temel İşlemler']),
    r(4, 'Verilen problemi çözmek üzere farklı algoritmalar tasarlar.\nAlgoritmanın hatalarını giderir.',
      ['1.2.1. Aritmetiksel Operatörler', '1.2.2. Karşılaştırma Operatörleri', '1.2.3. Mantıksal Operatörler', '1.2.4. İşlem Önceliği']),
    r(4, 'Verilen problemin çözümüne uygun akış şemaları oluşturur.',
      ['1.3. Algoritmalar', '1.3.1. Sözde Kod (Pseudo-code)', '1.3.2. Problem Çözmede Algoritma Hataları', '1.4. Akış Diyagramları']),
    r(4, 'Programlama dilinin özelliklerini ve diğer programlama dillerinden farklarını açıklar.',
      ['1.4.1. Flowcart (Akış Diyagramı) Hazırlama Programının Kurulumu', '1.4.2. Doğrusal Akış Şeması Örnekleri', '1.4.3. Karar İfadeleri Kullanılarak Hazırlanan Akış Şeması Örnekleri', '1.4.4. Döngüler Kullanılarak Hazırlanan Akış Şeması Örnekleri']),
    r(4, 'Programlama dilini bilgisayarına kurar.',
      ['ÖĞRENME BİRİMİ 3: PROGRAMLAMA DİLİ TEMELLERİ', '3. PROGRAMLAMA DİLİ TEMELLERİ', '3.1. Program ve Yazılım']),
    r(4, 'Programlama dilini kullanmak için gerekli araçları kurar.',
      ['3.2. Programlama Dili', '3.3. Neden Python?', '3.4. Python ile Neler Yapılabilir?']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['3.5. Python Kurulumu', '3.6. Python İçin Gerekli Araçlar', '3.6.1. Editör Kurulumu']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['3.6.2. Kütüphane Kullanımı', 'ÖĞRENME BİRİMİ 4: VERİ YAPILARI', '4. VERİ YAPILARI', '4.1. Değişken ve Sabit Kavramları', '4.1.1. Değişken Tanımlama', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav', '4.2. Operatörler', '4.2.1. Aritmetiksel Operatörler', '4.2.2. Atama Operatörleri', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(4, 'Programlama dilinde değişken, sabit ve operatörleri kullanır.',
      ['4.2.3. Karşılaştırma Operatörleri', '4.2.4. Mantıksal Operatörler']),
    r(4, 'Programlama dilinde veri tiplerini amacına uygun kullanır.',
      ['4.2.5. Kimlik Operatörleri', '4.3. Veri Tipleri', '4.3.1. String (Metinsel) Veri Tipi']),
    r(4, 'Programlama dilinde tanımladığı veriye ait temel fonksiyonların yer aldığı programları geliştirir.',
      ['4.3.2. Numbers (Sayısal) Veri Tipleri']),
    r(4, 'Farklı veri tiplerini (listeler, sözlükler vb.) kullanarak programlar geliştirir.',
      ['4.3.3. Listeler', '4.3.4. Tuple (Demet) Veri Tipi']),
    r(4, 'Farklı veri tiplerini (listeler, sözlükler vb.) kullanarak programlar geliştirir.',
      ['4.3.5. Dictionary (Sözlük) Veri Tipi', '4.3.6. Set (Küme) Veri Tipi']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['ÖĞRENME BİRİMİ 5: KARAR VE DÖNGÜ YAPILARI', '5. KARAR VE DÖNGÜ YAPILARI', '5.1. Karar Yapıları', '5.1.1. If-Else Yapısı']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['5.1.2. If-Elif-Else Yapısı', '1.Dönem 2.Sınav']),
    r(4, 'Kontrol yapılarını kullanarak programlar geliştirir.',
      ['5.1.3. İç İçe İfadeler']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.1. For Döngüsü']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.1.1. Range Kullanımı', '5.2.1.2. In Kullanımı']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.2. While Döngüsü']),
    r(4, 'Tekrarlı yapıları kullanarak programlar geliştirir.',
      ['5.2.3. Break ve Continue Deyimleri']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['ÖĞRENME BİRİMİ 6: FONKSİYONLAR', '6. FONKSİYONLAR', '6.1. Fonksiyon', '6.1.1. Fonksiyonların Kullanımı']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.1.2. Gömülü Fonksiyonların ve Modüllerin Kullanımı', '6.2. Fonksiyon Tanımlama']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.2.1. Fonksiyon Düzenleme', '6.2.2. Parametre Kavramı ve Fonksiyonlar ile Parametre Kullanımı', '6.2.3. Değer Döndürme ve Return İfadesi', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(4, 'Program dilinde fonksiyonları kullanır.',
      ['6.3. Lambda Fonksiyonlar']),
    r(4, 'Fonksiyon türlerine göre programlar geliştirir.',
      ['6.4. Özyinelemeli Fonksiyonlar', '6.4.1. Özyinelemeli Fonksiyonların Çalışma Şekli', '2.Dönem 1.Sınav']),
    r(4, 'Fonksiyon türlerine göre programlar geliştirir.',
      ['6.5. Fonksiyonlarda Kullanılan Değişkenlerin Kapsamı', 'ÖĞRENME BİRİMİ 7: TARİH VE STRİNG (METİN) İŞLEMLERİ', '7. TARİH VE METİN İŞLEMLERİ']),
    r(4, 'Tarih nesnesi oluşturur.\nTarih bilgisini biçimlendirir.',
      ['7.1. Tarih Nesnesi', '7.1.1. String (Metin) Olarak Girilen Değerlerin Tarih Bilgisinin Biçimlendirilmesi']),
    r(4, 'Metin bilgisini biçimlendirir.',
      ['7.2. String (Metin) İşlemleri', '7.2.1. String Verileri Birleştirme', '7.2.2. String Veri İçerisindeki Bir Karaktere Erişme', '7.2.3. String Verinin Uzunluğu']),
    r(4, 'Metin bilgisini biçimlendirir.',
      ['Çocuk, insan sevgisi ve evrensellik', '7.2.4. String Veriyi Parçalama (Slice) ve Bölme (Split)', '7.2.5. String Veri İçinde Karakter Değiştirme, Karakter Ekleme ve Çıkarma', '7.2.6. String Veri İçinde Bir Karakterin Yerini veya Metnin Karakteri İçerip İçermediğini Bulma']),
    r(4, 'İstisna işlemlerini açıklar.',
      ['7.2.7. String Veri İle Büyük ve Küçük Harf Değişimi Yapma', 'ÖĞRENME BİRİMİ 8: HATA YAKALAMA İŞLEMLERİ', '8. HATA YAKALAMA İŞLEMLERİ']),
    r(4, 'Try-except bloklarını kullanır.',
      ['8.1. Hata Kavramı ve Hata Türleri', '8.1.1. Hata Nedir?', '8.1.2. Hata Türleri']),
    r(4, 'Finally bloğunu kullanır.',
      ['8.2. Hata Yakalama', '8.3. Python Hata Türleri', '8.3.1. Birden Fazla (Except) Bloğu', '8.3.2. (as) İfadesi ile Orijinal Hata Mesajı Gösterme', '8.3.3. (finally) Bloğu', '8.3.4. (raise) İfadesi', '8.3.5. (assert) İfadesi', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(4, 'Programlama dilinde dosya okuma işlemlerini yapar.',
      ['ÖĞRENME BİRİMİ 9: DOSYA İŞLEMLERİ', '9. DOSYA İŞLEMLERİ', '9.1. Çalışma Dizini Ayarları ve Klasör Oluşturma', '9.1.1. Yol (Path) Tanımlama']),
    r(4, 'Dosya oluşturma ve yazma işlemlerini yapar.',
      ['9.1.2. Yolu Bilinen Klasör veya Dosyanın Var Olup Olmadığını Kontrol Etme', '9.1.3. Klasör Oluşturma', '9.1.4. Dosyalara Erişme ve Okuma']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['2.Dönem 2.Sınav', '9.2. Dosya Oluşturma ve Yazma']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['9.3. Dosya Silme ve Yedekleme']),
    r(4, 'Dosya silme ve yedekleme işlemlerini yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== BİLİŞİM TEKNOLOJİLERİNİN TEMELLERİ (9. Sınıf) ====================
const bilisimTemelleri = {
  name: '9. Sınıf Bilişim Teknolojilerinin Temelleri',
  area: AREA,
  gradeLevel: '9.SINIF',
  courseName: 'Bilişim Teknolojilerinin Temelleri',
  weeklyHours: 3,
  defaultMethods: 'Anlatım, gösterip yaptırma, soru cevap, grup çalışması, beyin fırtınası, uygulama',
  defaultTools: "Bilgisayar, donanım birimleri, işletim sistemi kurulum cd'leri, el aletleri, ağ cihazları, çeşitli yazılımlar",
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(3, 'Bilişim teknolojilerini ve internet (genel ağ) ortamını kullanma ve yönetme sürecinde dikkat edilmesi gereken etik ilkeleri açıklar.',
      ['Öğrenme Birimi: BİLİŞİM ETİĞİ', '1. Bilişim Etiği', '1.1. Etik Ve Bilişim Etiği Kavramları', '1.1.1. Etik Ve Bilişim Etiği', '1.1.2. Bilişim Temel Hak Ve Özgürlükleri', '1.1.3. Kod Yazımında Etik İlkeler', '1.1.4. Sosyal Medya Etiği', '1.1.5. İnternet Etiği', 'Demokrasinin önemi']),
    r(3, 'Bilgi güvenliğinin önemini açıklar.\nBilgi güvenliğine yönelik tehditleri açıklar.',
      ['1.2. Bilgi Ve Bilgi Güvenliği', '1.3. Temel Güvenlik Prensipleri', '1.3.1. Bilgisayar Açılış Güvenliği', '1.3.2. Parola Güvenliği Prensipleri', '1.3.3. İnternet Erişim Güvenliği']),
    r(3, 'Kişisel bilgisayar ve ağ ortamında bilgi güvenliğini sağlamaya yönelik işlemleri yürütür.',
      ['1.3.4. E-Posta Güvenliği', '1.3.5. Sosyal Medyaya Erişim Güvenliği', '1.3.6. Dosya Erişim Ve Paylaşım Güvenliği', '1.3.7. Zararlı Yazılımlardan Korunma Prensipleri']),
    r(3, 'Fikri mülkiyet hakkını açıklar.',
      ['1.4. Fikrî Ve Sınai Mülkiyet', '1.4.1. Telif Hakkı', '1.4.2. Marka', '1.4.3. Patent', '1.4.4. Faydalı Model', '1.4.5. Tasarım', '1.4.6. Ticari Sır']),
    r(3, 'Birinci sanayi devrimini açıklar.\nİkinci sanayi devrimini açıklar.\nÜçüncü sanayi devrimini açıklar.',
      ['Öğrenme Birimi: DİJİTAL DÖNÜŞÜM', '2. Dijital Dönüşüm', '2.1. Birinci Sanayi Devrimi', '2.2. İkinci Sanayi Devrimi', '2.3. Üçüncü Sanayi Devrimi']),
    r(3, 'Dördüncü sanayi devrimini açıklar.\nDijital dönüşüm kavramlarını açıklar.\nBüyük veri teknolojilerini açıklar.',
      ['2.4. Dördüncü Sanayi Devrimi', '2.5. Dijital Dönüşüm Kavramları', '2.6. Büyük Veri Teknolojileri']),
    r(3, 'Arttırılmış gerçeklik ve sanallaştırmayı açıklar.\nSimülasyon sistemlerini açıklar.',
      ['2.7. Artırılmış Gerçeklik Ve Sanallaştırma', '2.8. Simülasyon Sistemleri', '2.8.1. Sanal Fabrika', '2.8.2. Dijital Fabrika', '2.8.3. Dijital İkiz']),
    r(3, 'Otomasyon ve sensör teknolojilerini açıklar.\nBulut bilişim sistemlerini açıklar.\nSiber güvenlik sistemlerini açıklar.',
      ['2.9. Otomasyon Ve Sensör Teknolojileri', '2.9.1. Sensörler', '2.9.2. Otomasyon Sistemlerinde Kullanılan Sensörler', '2.9.3. Akıllı Ev Sistemleri', '2.9.4. Akıllı Fabrikalar', '2.10. Bulut Bilişim Sistemleri', '2.11. Siber Güvenlik Sistemleri', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(3, 'Üretim ve hizmet süreçlerinde dijital izlenebilirlik sistemlerini (RFID, RTLS ilişkili teknolojiler) açıklar.\nAr-Ge projesi geliştirmeyi açıklar.',
      ['2.12. Üretim Ve Hizmet Süreçlerinde Dijital İzlenebilirlik Sistemleri', '2.12.1. RFID (Radio Frequency Identification)', '2.12.2. RTLS (Gerçek Zamanlı Yer Belirleme) Teknolojileri', '2.12.3. Beacon Teknolojileri', '2.13. Ar-Ge Projesi Geliştirme', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(3, 'Kullanım kılavuzuna uygun olarak anakartı montaj için hazırlar.',
      ['Öğrenme Birimi: İÇ DONANIM BİRİMLERİ', '3. İç Donanım Birimleri', '3.1. Anakartlar', '3.1.1. Statik Elektrik', '3.1.2. Bilgisayar Teknolojisinde Statik Elektrik', '3.1.3. Statik Elektriğin Önlenmesi']),
    r(3, 'Kullanım kılavuzuna uygun olarak anakartı montaj için hazırlar.',
      ['3.1.4. Anakart Ve Görevi', '3.1.5. Anakart Standartları', '3.1.6. Anakart Bileşenleri']),
    r(3, 'Bileşen uyumluluğuna göre anakarta işlemciyi monte eder.',
      ['3.2. İşlemciler', '3.2.1. İşlemci Yapısı', '3.2.2. İşlemcinin Çalışma Prensibi', '3.2.3. İşlemci Çeşitleri', '3.2.4. İşlemci Soğutması', '3.2.5. İşlemci Montajı']),
    r(3, 'Bellek birimlerini anakart üzerine doğru monte eder.',
      ['3.3. Bellekler', '3.3.1. Belleklerin Yapısı Ve Çalışması', '3.3.2. Bellek Çeşitleri', '3.3.3. Bellek Seçimi', '3.3.4. Bellek Montajı']),
    r(3, 'Genişleme yuvası kartlarını anakart üzerine doğru monte eder.',
      ['3.4. Genişleme Yuvası Kartları', '3.4.1. Ekran Kartı', '3.4.2. Ses Kartı', '3.4.3. Ethernet Kartı']),
    r(3, 'Disk sürücülerini kasaya doğru monte eder.',
      ['3.5. Disk Sürücüler', '3.5.1. Sabit Sürücüler', '3.5.2. Sabit Disk Sürücü Kabloları', '3.5.3. Sabit Disk Seçimi', '3.5.4. Sabit Disk Montajı', '3.6. Optik Sürücüler', '3.6.1. Cd Sürücüler', '3.6.2. Dvd Sürücüler', '3.6.3. Bluray Sürücüler']),
    r(3, 'Anakartı kasa içine monte eder.',
      ['3.7. Bilgisayar Kasasına Anakart Montajı', '3.7.1. Güç Kaynağı', '3.7.2. Ön Panel Konnektörleri', '3.7.3. Anakartın Kasa İçine Montajı', '1.Dönem 2.Sınav']),
    r(3, 'Giriş birimleri bağlantılarını yapar.',
      ['Öğrenme Birimi: DIŞ DONANIM BİRİMLERİ', '4. Dış Donanım Birimleri', '4.1. Giriş Birimleri', '4.1.1. Klavye', '4.1.2. Fare (Mouse)']),
    r(3, 'Görüntüleme birimlerinin bağlantısını yapar.',
      ['4.2. Görüntüleme Birimleri', '4.2.1. Monitörler', '4.2.2. Projeksiyon Cihazları']),
    r(3, 'Yazıcıların kablo bağlantılarını yapar.',
      ['4.3. Yazıcılar', '4.3.1. Yazıcı Temel Kavramları', '4.3.2. Yazıcı Çeşitleri', '4.3.3. Yazıcı Bağlantı Arabirimleri']),
    r(3, 'Görüntü işleme cihazlarının bağlantısını yapar.\nYönergelere uyarak sistemin ilk açılış ayarlarını yapar.',
      ['4.4. Görüntü İşleme Cihazları', '4.4.1. Tarayıcı (Scanner)', '4.4.2. Dijital Fotoğraf Makinesi', '4.4.3. Ağ Kameraları (Webcam)']),
    r(3, 'Kapalı kaynak kodlu işletim sistemi kurulumunu yapar.\nKapalı kaynak kodlu işletim sisteminde sürücülerin ve yardımcı yazılımların kurulumunu yapar.',
      ['4.4.4. Hafıza Kartları', '4.4.5. Kart Okuyucular', 'Öğrenme Birimi: İŞLETİM SİSTEMLERİ VE KURULUMLARI']),
    r(3, 'Açık kaynak kodlu işletim sistemi kurulumunu yapar.\nAçık kaynak kodlu işletim sisteminde sürücülerin ve yardımcı yazılımların kurulumunu yapar.',
      ['5. İşletim Sistemleri Ve Kurulum', '5.1. İşletim Sistemi Kurulum Öncesi Açılış Ayarları', '5.1.1. Bıos', '5.1.2. Post']),
    r(3, 'Donanım sorunlarını tespit ederek giderir.\nYazılım sorunlarını tespit ederek giderir.\nİşletim sistemi sorunlarını tespit ederek giderir.',
      ['5.1.3. Bıos Ayarları', '5.1.4. Bıos Uyarıları', '5.2. Kapalı Kaynak Kodlu İşletim Sistemi Kurulumu']),
    r(3, 'Kapalı kaynak kodlu işletim sistemi uygulama ayarlarını yapar.\nAçık kaynak kodlu işletim sistemi uygulama ayarlarını yapar.',
      ['5.2.1. Kurulum Öncesi Ayarlar', '5.2.2. Kapalı Kaynak İşletim Sistemi Kurulumu', '5.3. Kapalı Kaynak Kodlu İşletim Sisteminde Sürücülerin Ve Yardımcı Yazılımların Kurulumu', '5.3.1. İnternet Erişimi Sağlama']),
    r(3, '',
      ['5.3.2. İşletim Sistemini Etkinleştirme', '5.3.3. İşletim Sistemini Güncel Tutma', '5.3.4. Aygıt Sürücülerinin Yüklenmesi', '5.3.5. Aygıt Yöneticisi Ve İşlevleri']),
    r(3, '',
      ['5.3.6. Sürücülerin Elle Kurulması', '5.3.7. Yardımcı Yazılımların Kurulumu', '5.4. Açık Kaynak Kodlu İşletim Sistemi Kurulumu', '5.5. Açık Kaynak Kodlu İşletim Sisteminde Sürücülerin Ve Yardımcı Yazılımların Kurulumu']),
    r(3, '',
      ['5.5.1. İşletim Sistemini Güncelleme', '5.5.2. İnternet Erişimi Sağlama', '5.5.3. Aygıt Sürücülerinin Yüklenmesi', '5.5.4. Yardımcı Yazılımların Kurulumu']),
    r(3, '',
      ['5.5.5. Açık Kaynak Ofis Programı', 'Atatürk\'ün vatan ve millet sevgisi', '5.6. İşletim Sistemlerinde Donanım Sorunlarını Giderme', '5.7. İşletim Sisteminde Yazılım Sorunlarını Giderme', '5.8. İşletim Sisteminde Diğer Sorunlar', '2.Dönem 1.Sınav', 'Öğrenme Birimi: İŞLETİM SİSTEMLERİ TEMEL KULLANIMI', '6. İşletim Sistemleri Temel Kullanım', '6.1. İşletim Sistemi Uygulama Ayarları', '6.1.1. Kullanıcı Hesapları', '6.1.2. Görünüm Ve Kişiselleştirme Ayarları']),
    r(3, 'Kapalı kaynak kodlu işletim sisteminde güvenlik yazılımlarını kullanarak işletim sisteminin korunmasını sağlar.\nAçık kaynak kodlu işletim sisteminde güvenlik yazılımlarını kullanarak işletim sisteminin korunmasını sağlar.',
      ['6.1.3. Saat, Dil Ve Bölge Ayarları', '6.1.4. Güvenlik Ayarları', 'Çocuk, insan sevgisi ve evrensellik']),
    r(3, 'Açık ve kapalı kodlu işletim sistemlerinde web tarayıcılarını kullanır.\nFiziksel ortama göre ağ sisteminin fiziksel bağlantı tasarımını yapar.\nFiziksel ortama ve ağ çeşidine göre ağ topolojisini seçer.\nAğ çeşidi ve fiziksel ortama göre ağ cihazlarının fiziksel bağlantılarını yapar.',
      ['6.2. İşletim Sistemlerinde Web Tarayıcıları Kullanımı', '6.2.1. Kapalı Kaynak İşletim Sisteminde Web Tarayıcı Kurulumu', '6.2.2. Açık Kaynak İşletim Sisteminde Web Tarayıcı Kurulumu', 'Öğrenme Birimi: AĞ TEMELLERİ', '7. Ağ Temelleri']),
    r(3, 'Sistem güvenliği için iletim katmanı portlarını kullanır.\nTalimatlara göre uygulama katmanı uygulamalarını kullanır.\nAğ hizmetlerine göre ağ protokolünü yapılandırır.',
      ['7.1. Ağ Sistemleri', '7.1.1. Veri İletimi', '7.1.2. Veri İletim Yöntemleri']),
    r(3, 'Ağ cihazlarına doğru TCP/IP adres girişini yapar.\nAğı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['7.1.3. Ağ Çeşitleri', '7.1.4. Coğrafi Yapıya Göre Bilgisayar Ağları', '7.1.5. Fiziksel Topolojilere Göre Bilgisayar Ağları', '7.1.6. Organizasyon Yapısı']),
    r(3, '',
      ['7.2. Ağ Modeli', '7.2.1. Veri Haberleşmede Katman Kullanımı', '7.2.2. Osı Modeli', '7.2.3. Tcp / Ip Modeli', '7.2.4. İletişim Protokolleri', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(3, '',
      ['7.3. Ağ Cihazları Ve Ağ Kabloları', '7.3.1. Ağ Cihazları', '7.3.2. Ağ Kabloları']),
    r(3, '',
      ['7.4. Kablolama', '7.4.1. Kablo Hazırlama', '7.4.2. Yapısal Kablolama']),
    r(3, '',
      ['7.5. Ip Adresleme', '2.Dönem 2.Sınav', '7.5.1. Ipv4 (İnternet Protokol Versiyon 4)']),
    r(3, 'Ağı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['7.5.2. Ethernet Kartı']),
    r(3, 'Ağı isteğe uygun alt ağlara ayırır.\nEthernet kartı bağlantısını yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== NESNE TABANLI PROGRAMLAMA (10. Sınıf) ====================
const nesneTabanli = {
  name: '10. Sınıf Nesne Tabanlı Programlama',
  area: AREA,
  gradeLevel: '10.SINIF',
  courseName: 'Nesne Tabanlı Programlama',
  weeklyHours: 10,
  defaultMethods: 'Anlatım, soru-cevap, uygulamalı gösteri, araştırma, uygulama, bireysel öğrenme, beyin fırtınası',
  defaultTools: 'Ders kitabı, bilgisayar, akıllı tahta, görsel programlama ortamı, veritabanı programı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(10, 'Yazım hatalarını dikkate alarak nesne tabanlı programlama çalışma ortamını kullanır.',
      ['ÖĞRENME BİRİMİ: ÇALIŞMA ORTAMI VE TEMEL İŞLEMLER', '1.1. NESNE TABANLI PROGRAMLAMA ÇALIŞMA ORTAMI', '1.2. C# PROGRAMLAMA DİLİ', '1.3. .NET FRAMEWORK', '1.3.1. C# ve .NET Framework İlişkisi', '1.3.2. .NET Framework Çalışma Mantığı', 'Demokrasinin önemi']),
    r(10, 'Yazım hatalarını dikkate alarak isim uzaylarını kullanır.',
      ['1.4. KOD EDİTÖRÜ ARAYÜZ EKRANI', '1.4.1. FORM EKRANI', '1.4.2. Araç Kutusu (Toolbox)', '1.4.3. Özellikler (Properties)', '1.4.4. Olaylar (Events)', '1.4.5. Çözüm Penceresi (Solution Explorer)', '1.4.6. Hata Listesi (Error List)', '1.5. İSİM UZAYLARI (NAMESPACE)']),
    r(10, 'Tanımlama kurallarını dikkate alarak değişkenleri ve temel veri türlerini kullanır.\nİşlem önceliğine göre aritmetiksel operatörleri kullanır.',
      ['1.6. DEĞİŞKENLER VE TEMEL VERİ TÜRLERİ', '1.6.1. Temel Veri Türleri', '1.6.2. Değişken Tanımlama', '1.6.3. Değişkene Değer Atama', '1.6.4. Değişken İsimlendirme Kuralları', '1.6.5. Değişken Veri Türü Dönüştürme (Convert) İşlemleri', '1.7. ARİTMETİKSEL OPERATÖRLER', '1.7.1. İşlem Önceliği']),
    r(10, 'Yazım kurallarına dikkat ederek şart ifadelerini kullanır.',
      ['ÖĞRENME BİRİMİ: KARAR VE DÖNGÜ YAPILARI', '2.1. KARAR İFADELERİ', '2.1.1. Karşılaştırma Operatörleri', '2.1.2. if Yapısı', '2.1.3. if-else Yapısı', '2.1.4. else if Yapısı', '2.1.5. İç İçe Şart İfadeleri', '2.1.6. Switch-Case']),
    r(10, 'Mantıksal operatörleri öncelik sırasına uygun kullanır.',
      ['2.2. MANTIKSAL OPERATÖRLER', '2.2.1. AND (&&) Operatörü', '2.2.2. OR (||) Operatörü', '2.2.3. Mantıksal Operatör Önceliği', '2.2.4. NOT (!) Operatörü']),
    r(10, 'Yazım formatına dikkat ederek döngü yapılarını kullanır.',
      ['2.3. DÖNGÜLER', '2.3.1. Sayaçlar', '2.3.2. Artırma ve Azaltma Operatörleri', '2.3.3. For Döngüsü', '2.3.4. While Döngüsü', '2.3.5. Do-while Döngüsü']),
    r(10, 'Programda hata ayıklaması yapar.',
      ['2.3.6. Döngüyü Kesme (Durdurma)', '2.3.7. Döngüyü Devam Ettirme', '2.4. HATA AYIKLAMA', '2.4.1. Try-Catch-Finally Bloku']),
    r(10, 'İhtiyaca uygun sınıf tanımlaması yapar.',
      ['ÖĞRENME BİRİMİ: SINIFLAR (CLASSES)', '3.1. NESNE TABANLI PROGRAMLAMAYA GİRİŞ', '3.1.1. NTP Öncesi', '3.1.2. NTP Temel Prensipleri', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(10, 'Sınıfa ait özellikleri açıklar.',
      ['3.2. SINIFLAR VE NESNELER', '3.2.1. Sınıf Tanımlama', '3.2.2. Nesne Oluşturma', '3.3. KAPSÜLLEME, ALANLAR VE ÖZELLİKLER (ENCAPSULATION, FIELDS, PROPERTIES)', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(10, 'Sınıfa ait özellikleri açıklar.',
      ['3.4. ERİŞİM BELİRLEYİCİLER (ACCESS MODIFIERS)', '3.5. ALANLAR (FIELDS)', '3.6. ÖZELLİKLER (PROPERTIES)', '3.6.1. Sadece Okunabilir Özellikler', '3.6.2. Sadece Yazılabilir Özellikler']),
    r(10, 'Tanımlama adımlarına dikkat ederek metotları tanımlar.',
      ['3.7. METOTLAR (METHODS)', '3.7.1. Varsayılan Değerli Parametreler (Optional Parameters)', '3.7.2. İsimlendirilmiş Parametreler (Named Parameters)', '3.7.3. Parametre Dizileri', '3.7.4. Metodu Sonlandırma', '3.7.5. Metot Aşırı Yüklemeleri (Method Overloads)']),
    r(10, 'Farklı metot imzaları tanımlayarak metotları aşırı yükler.\nSınıfların erişim türünü belirler.',
      ['3.8. YAPICI VE YIKICI METOTLAR', '3.8.1. Yapıcı Metotlar (Constructors)', '3.8.2. Yıkıcı Metotlar (Destructors)', '3.9. DEĞER VE REFERANS TİPLER', '3.9.1. Metotlarda ref ve out Kullanımı']),
    r(10, 'Kapsülleme (Encapsulation), Kalıtım (Inheritance) ve Çok biçimlilik (Polymorphism) prensiplerini kullanır.',
      ['3.10. KALITIM (INHERITANCE)', '3.10.1. Hiyerarşik Kalıtım', '3.10.2. new Operatörüyle Metot Gölgeleme (Shadowing)', '3.10.3. Sanal Metotlar (Virtual Methods)']),
    r(10, 'Kapsülleme (Encapsulation), Kalıtım (Inheritance) ve Çok biçimlilik (Polymorphism) prensiplerini kullanır.',
      ['3.11. SOYUT SINIFLAR (ABSTRACT CLASSES)', '3.12. ARAYÜZLER (INTERFACES)', '3.13. ÇOK BİÇİMLİLİK (POLYMORPHISM)', '3.14. STATİK SINIFLAR (STATIC CLASSES)']),
    r(10, 'Kapsülleme (Encapsulation), Kalıtım (Inheritance) ve Çok biçimlilik (Polymorphism) prensiplerini kullanır.',
      ['3.15. İSİMSİZ SINIFLAR', '3.16. MÜHÜRLÜ SINIFLAR (SEALED CLASSES)', '3.17. PARÇALI SINIFLAR (PARTIAL CLASSES)', '3.18. ENUMS (NUMARALANDIRMALAR)']),
    r(10, 'Dizi tanımlama kurallarına dikkat ederek dizileri kullanır.',
      ['ÖĞRENME BİRİMİ: DİZİLER (ARRAYS) VE KOLEKSİYONLAR (COLLECTIONS)', '4.1. DİZİLER', '4.1.1. Bir Boyutlu Diziler', '4.1.2. Bir Boyutlu Dizilerin Oluşturulması', '4.1.3. Bir Boyutlu Dizilere Değer Aktarma', '4.1.4. Bir Boyutlu Dizi Elemanlarına Erişim', '1.Dönem 2.Sınav']),
    r(10, 'Dizi tanımlama kurallarına dikkat ederek dizileri kullanır.',
      ['4.1.5. Dizilerde Foreach Döngüsü Kullanımı', '4.1.6. Bir Boyutlu Dizilerde Kullanılan Özellikler ve Metotlar', '4.1.7. Çok Boyutlu Diziler', '4.1.8. İki Boyutlu Dizi Tanımlama', '4.1.9. İki Boyutlu Diziye Değer Aktarma', '4.1.10. İki Boyutlu Dizi Elemanlarına Erişim']),
    r(10, 'Koleksiyon sınıflarının farklarına göre kullanır.',
      ['4.2. KOLEKSİYONLAR', '4.2.1. Boxing (Kutulama)-Unboxing (Kutu Açma)', '4.2.2. ArrayList Koleksiyonu', '4.2.3. List Koleksiyonu']),
    r(10, 'Koleksiyon sınıflarının farklarına göre kullanır.',
      ['4.2.4. Queue-Stack Koleksiyonları', '4.2.5. Dictionary Koleksiyonu', '4.2.6. Hashtable Koleksiyonu', '4.2.7. SortedList Koleksiyonu']),
    r(10, 'Form oluşturur.',
      ['ÖĞRENME BİRİMİ: FORM UYGULAMALARI', '5.1. FORMLAR', '5.1.1. Form Sınıfı']),
    r(10, 'Form oluşturur.',
      ['5.1.2. Kontrol Sınıfı', '5.1.3. Konteyner Kontrolleri']),
    r(10, 'Form oluşturur.',
      ['5.2. MENÜLER', '5.2.1. MenuStrip Kontrolü', '5.2.2. ContextMenuStrip Kontrolü']),
    r(10, 'İstenilen özellik ve içerikteki iletişim kutularıyla çalışır.',
      ['5.3. İLETİŞİM KUTULARI (DIALOG BOXES)', '5.3.1. Mesaj İletişim Kutusu (MessageBox)', '5.3.2. Dosya Kaydet İletişim Kutusu (SaveFileDialog)']),
    r(10, 'İstenilen özellik ve içerikteki iletişim kutularıyla çalışır.',
      ['5.3.3. Dosya Aç İletişim Kutusu (OpenFileDialog)', '5.3.4. Yazdırma İletişim Kutusu (PrintDialog)', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(10, 'İstenilen özellik ve içerikteki iletişim kutularıyla çalışır.',
      ['5.3.5. Yazı Tipi İletişim Kutusu (FontDialog)', '5.3.6. Renk İletişim Kutusu (ColorDialog)', '5.4. VERİ DOĞRULAMA (VALIDATION)']),
    r(10, 'İstenilen özellik ve içerikteki iletişim kutularıyla çalışır.',
      ['5.4.1. İpucu (ToolTip)', '5.4.2. Veri Girişi Doğrulama (Input Validation)', '5.4.3. Veri Girişi Maskeleme (MaskedTextBox)', '2.Dönem 1.Sınav', '5.5. VERİ BAĞLAMA (DATA BINDING)']),
    r(10, 'İstenilen özellik ve içerikteki iletişim kutularıyla çalışır.',
      ['5.5.1. Basit Veri Bağlama (Simple Data Binding)', '5.5.2. Kompleks Veri Bağlama (Complex Data Binding)', 'ÖĞRENME BİRİMİ: VERİ TABANI İŞLEMLERİ']),
    r(10, 'Açık kaynak veri tabanı yazılımını kurar.',
      ['6.1. VERİ TABANI YAZILIMININ KURULUMU', '6.1.1. Veri Tabanı Yönetim Sistemi (Database Management System)', '6.1.2. SQL (Structured Query Language)', '6.1.3. Büyük Veri (Big Data) ve Veri Madenciliği']),
    r(10, 'Veri tabanı oluşturur.\nVeri tabanında tabloları kullanır.',
      ['6.1.4. MySQL Veri Tabanı', '6.2. MYSQL SERVER ARAYÜZ (WORKBENCH) EKRANI', '6.3. VERİ TÜRLERİ', '6.4. VERİ TABANI TASARIMI', '6.4.1. Veri Tabanı Oluşturma']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.4.2. Veri Tabanında Anahtarlar (Keyler)', '6.4.3. Tablo Oluşturma', '6.5. TABLOLARI İLİŞKİLENDİRME', '6.5.1. İlişkisel Veri Tabanları', '6.5.2. Tablolar Arası Bağlantı Yapılması', 'Çocuk, insan sevgisi ve evrensellik', '6.6. VERİ TABANINA BİLGİ GİRİŞİ', '6.7. SQL KOMUTLARI KULLANIMI', '6.7.1. Select Deyimi', '6.7.2. Where Şart İfadesi', '6.7.3. Karşılaştırma Operatörleri', '6.7.4. Mantıksal Operatörler']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.7.5. Arama Operatörü', '6.7.6. Order By Komutu (Sıralama)', '6.7.7. Insert Into Komutu (Kayıt Ekleme)', '6.7.8. Update Komutu (Kayıt Güncelleme)']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.7.9. Delete Komutu (Kayıt Silme)', '6.7.10. Create', '6.7.11. Alter', '6.7.12. Drop']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.8. MYSQL VERİ TABANI ALMA VE YÜKLEME', '6.9. SQL VE NTP BAĞLANTISI', '6.9.1. Form Tasarımları', '6.9.2. Form Özellikleri', '6.9.3. TabControl Bileşeni', '6.9.4. ImageList Bileşeni']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.10. ADO.NET', '6.11. VERİ TABANI BAĞLANTISI VE BİLEŞENLERİN EKLENMESİ', '6.11.1. MySQL Bağlantı Kontrolü']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.11.2. MySQL Connection String', '6.11.3. Projeye Giriş', '6.11.4. DataGridView Bileşeni', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.11.5. Projenin Kodlamasına Giriş', '6.11.6. Dersler Sekmesi', '6.11.7. Notlar Sekmesi', '6.11.8. Öğrenci İşlemleri Sekmesi', '6.11.9. Anasayfa Sekmesinin Doldurulması', '6.12. KAYIT EKLEME', '6.13. ARAMA METODU', '6.14. EKLEME, SİLME VE GÜNCELLEME İŞLEMLERİ', '6.14.1. Öğrenci Sekmesi İşlemleri', '2.Dönem 2.Sınav', '6.14.2. Notlar Sekmesi', '6.14.3. Dersler Sekmesi']),
    r(10, 'SQL komutlarını kullanır.',
      ['6.15. KURULUM (SETUP) HAZIRLAMA', '6.16. ENTITY FRAMEWORK']),
    r(10, 'SQL komutlarını kullanır.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== WEB PROGRAMCILIĞI (Seçmeli) ====================
const webProgramciligi = {
  name: 'Web Programcılığı (Seçmeli)',
  area: AREA,
  gradeLevel: 'SEÇMELİ',
  courseName: 'Web Programcılığı',
  weeklyHours: 3,
  defaultMethods: 'Anlatım, araştırma, gösterip yaptırma, soru-cevap, uygulama, bireysel öğretim, beyin fırtınası',
  defaultTools: 'Akıllı tahta/projeksiyon, bilgisayar, internet bağlantısı, açık kaynak yazılımlar',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(3, 'PHP\'nin özelliklerini ve diğer programlama dillerinden farklarını açıklar.',
      ['1. ÖĞRENME BİRİMİ: ETKİLEŞİM VE VERİ YÖNETİMİ (PHP)', '1.1. PHP DİLİ VE ÖZELLİKLERİ', '1.1.1. PHP Programlama Dilinin Yapısı', '1.1.2. PHP Dilinin Avantajları Ve Dezavantajları']),
    r(3, 'PHP ve gerekli bileşenleri bilgisayarına kurar.',
      ['Demokrasinin önemi', '1.2. PHP KURULUMU']),
    r(3, 'PHP ile farklı türde değişken tanımlar.',
      ['1.2.1. Apache, PHP ve MySQL Kurulum Adımları', '1.3. DEĞİŞKEN VE SABİTLER']),
    r(3, 'Mantıksal operatörleri kullanır.',
      ['1.3.1. Primatif Veri Tipleri Ve Primatif Olmayan Veri Tipleri', '1.3.2. Boolean, İnteger, Float, String, Null, Array, Object Veri Tipleri', '2. ÖĞRENME BİRİMİ: KARAR VE DÖNGÜ YAPILARI', '2.1. MANTIKSAL OPERATÖRLER', '2.1.1. Ve (AND) Operatörü']),
    r(3, 'Karar kontrol deyimlerini kullanır.',
      ['2.1.2. Veya (OR) Operatörü', '2.1.3. XOR Operatörü', '2.1.4. Değil (NOT) Operatörü', '2.1.5. Mantıksal Operatörlerin Doğruluk Tablosu']),
    r(3, 'Döngü deyimlerini kullanır.',
      ['2.2. KARAR KONTROL DEYİMLERİ', '2.2.1. If-else Kontrol Deyimi', '2.2.2. Switch-Case Kontrol Deyimi']),
    r(3, 'Döngü deyimlerini kullanır.',
      ['2.3. DÖNGÜ DEYİMLERİ', '2.3.1. While Döngüsü']),
    r(3, 'Düzenli ifadeleri kullanır.',
      ['2.3.2. Do-While Döngüsü', '2.3.3. For Döngüsü', '2.3.4. For-Each Döngüsü', '2.3.5. Break ve Continue Deyimleri']),
    r(3, 'Dizi yapılarını kullanır.',
      ['2.4. VERİLER ÜZERİNDE DÖNGÜ KONTROLLERİ', '2.5. DÜZENLİ İFADELER', '2.5.1. Düzenli İfadelerin (Regex) Tanımı']),
    r(3, 'Dizi elemanları üzerinde işlemler yapar.',
      ['2.5.2. Düzenli İfade Kuralları', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(3, 'PHP programlama dilinde fonksiyon tanımlar.',
      ['3. ÖĞRENME BİRİMİ: DİZİ YAPILARI', '3.1. DİZİ YAPILARI', '3.1.1. Tek Boyutlu Diziler', '3.1.2. Çağrışımsal (Associative) Diziler', '3.1.3. Çok Boyutlu Diziler', 'Atatürk\'ün eğitime ve bilime verdiği önem', '3.2. DİZİLERLE İŞLEMLER', '3.2.1. Döngü İle Dizi Elemanlarına Erişim', '3.2.2. Oluşturulan Dizilere Erişim Yöntemleri', '4. ÖĞRENME BİRİMİ: FONKSİYONLAR', '4.1. PHP\'DE FONKSİYONLAR', '4.1.1. Programcı (Kullanıcı) Tanımlı Fonksiyonlar', '4.1.2. Hazır (Yerleşik) Fonksiyonlar']),
    r(3, 'Fonksiyon parametrelerini kullanır.\nDeğer döndüren fonksiyonları kullanır.',
      ['4.2. FONKSİYON PARAMETRELERİ', '4.2.1. Parametresiz Fonksiyonlar', '4.2.2. Parametreli Fonksiyonlar', '4.3. DEĞER DÖNDÜREN FONKSİYONLAR']),
    r(3, 'Tarih/saat fonksiyonlarını kullanır.',
      ['4.4. TARİH / SAAT FONKSİYONLARI']),
    r(3, 'Metin fonksiyonlarını kullanır.',
      ['4.5. METİN FONKSİYONLARI']),
    r(3, 'Metin fonksiyonlarını kullanır.',
      ['4.6. MATEMATİK FONKSİYONLARI']),
    r(3, 'HTML Form elemanlarını tanımlar.',
      ['5. ÖĞRENME BİRİMİ: FORM İŞLEMLERİ', '5.1. HTML FORM ELEMANLARI', '5.1.1. Html Form Öğeleri', '5.1.2. Form Oluşturma Uygulamaları', '1.Dönem 2.Sınav']),
    r(3, 'Get ile Post arasındaki farkı açıklar.',
      ['5.2. GET VE POST METOTLARI', '5.2.1. Get ve Post Olayları Arasındaki Farklar', '5.2.2. Get ve Post Uygulamaları']),
    r(3, 'Güvenli form tanımlar.',
      ['5.3. GÜVENLİ FORM OLUŞTURMA', '5.3.1. Resim Doğrulama Uygulaması']),
    r(3, 'Formlarda dosya bileşenini kullanır.',
      ['5.4. FORMDA DOSYA BİLEŞENLERİ KULLANMA']),
    r(3, 'İstisna işlemlerini açıklar.',
      ['6. ÖĞRENME BİRİMİ: HATA YAKALAMA İŞLEMLERİ', '6.1. PHP İSTİSNA İŞLEMLERİ', '6.1.1. Hata Türleri']),
    r(3, 'Try-catch bloklarını kullanır.\nFinally bloğunu kullanır.',
      ['6.2. Try-Catch Yapısı', '6.3. Finally Yapısı']),
    r(3, 'Yeni dosya oluşturur.',
      ['7. ÖĞRENME BİRİMİ: DOSYA İŞLEMLERİ', '7.1. PHP\'DE KLASÖR VE DOSYA İŞLEMLERİ', '7.1.1. Dosya İçe Aktarma Fonksiyonları']),
    r(3, 'Yeni dosya oluşturur.\nVar olan bir dosyayı açar.',
      ['7.2. PHP\'DE DOSYA OLUŞTURMA', '7.3. PHP\'DE DOSYA AÇMA']),
    r(3, 'Dosyanın içine bilgi ekler.',
      ['7.4. PHP\'DE DOSYA İÇİNE BİLGİ EKLEME', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(3, 'Dosyayı siler.',
      ['7.5. PHP\'DE DOSYAYI SİLME']),
    r(3, 'Kullanıcı bilgilerinin hatırlanmasında çerezleri kullanır.',
      ['8. ÖĞRENME BİRİMİ: OTURUM YÖNETİMİ', '8.1. ÇEREZ YÖNETİMİ', '8.1.1. Çerez (Cookie) Kavramı', '8.1.2. Çerez Uygulamaları', '2.Dönem 1.Sınav']),
    r(3, 'Oturum mimarisini açıklar.',
      ['8.2. OTURUM MİMARİSİ VE SESSION GENEL DEĞİŞKENİ', '8.2.1. Oturum (Session) Mimarisi', '8.2.2. Session Uygulamaları']),
    r(3, 'SESSION genel değişkenini kullanır.',
      ['9. ÖĞRENME BİRİMİ: MYSQL VERİ TABANI KULLANIMI', '9.1. MySQL TEMEL KAVRAMLARI']),
    r(3, 'Veri tabanı temel kavramlarını açıklar.',
      ['9.1.1. Sayı Veri Türleri', '9.1.2. Metin Veri Türleri', '9.1.3. Tarih ve Saat Veri Türleri', 'Çocuk, insan sevgisi ve evrensellik', '9.2. UYGULAMA SUNUCUSUNUN KURULMASI VE YÖNETİLMESİ']),
    r(3, 'Uygulama sunucusunu kurar ve yönetir.\nVeri tabanı oluşturur.\nVeri tabanı içine tablo oluşturur.',
      ['9.2.1. MySQL Komut Satırı Kullanımı', '9.2.2. phpMyAdmin Kullanımı', '9.2.3. Tablo Oluşturma İşlemleri', '9.2.3. Tablo İlişkileri Kurma']),
    r(3, '',
      ['9.3. PHP İLE VERİ TABANI BAĞLANTISI YAPMA', '9.4. PHP İLE VERİ TABANI OLUŞTURMA', '9.5. PHP İLE TABLO OLUŞTURMA İŞLEMLERİ', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(3, 'PHP ile veri tabanı bağlantısı yapar.', ['']),
    r(3, 'MySql ile veri tabanı ve tablo oluşturma işlemlerini yapar.', ['']),
    r(3, 'PHP ile MySql ile veri ekleme, silme, oluşturma işlemlerini yapar.',
      ['9.6. PHP İLE MySQL VERİ TABANINDA VERİ EKLEME, SİLME, GÜNCELLEME İŞLEMLERİ', '9.6.1. Veri Ekleme', '9.6.2. Veri Silme']),
    r(3, 'PHP ile MySql veritabanında veri listeleme işlemlerini yapar.',
      ['9.6.3. Veri Güncelleme', '9.7. PHP İLE MySQL VERİ TABANINDA VERİ LİSTELEME İŞLEMLERİ', '2.Dönem 2.Sınav']),
    r(3, 'PHP ile MySql veritabanında veri listeleme işlemlerini yapar.',
      ['9.7. PHP İLE MySQL VERİ TABANINDA VERİ LİSTELEME İŞLEMLERİ']),
    r(3, 'PHP ile MySql veritabanında veri listeleme işlemlerini yapar.',
      ['9.7. PHP İLE MySQL VERİ TABANINDA VERİ LİSTELEME İŞLEMLERİ']),
    r(3, 'PHP ile MySql veritabanında veri listeleme işlemlerini yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== WEB TABANLI UYGULAMA GELİŞTİRME (11. Sınıf) ====================
const webTabanli = {
  name: '11. Sınıf Web Tabanlı Uygulama Geliştirme',
  area: AREA,
  gradeLevel: '11.SINIF',
  courseName: 'Web Tabanlı Uygulama Geliştirme',
  weeklyHours: 8,
  defaultMethods: 'Anlatım, araştırma, gösteri, örnek olay, soru-cevap, uygulama, bireysel öğretim, beyin fırtınası',
  defaultTools: 'Etkileşimli tahta veya projeksiyon, bilgisayar, internet bağlantısı, kodlama editörleri, görsel ve videolar, ders kitabı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(8, 'Web sayfası yayınlama ile ilgili temel kavramları açıklar.\nWeb yazılımcısı rollerini açıklar.\nİşaretleme Dili (HTML) kodlarının kullanılabileceği editörlere örnek verir.\nBasamaklı stil şablonu (CSS) kavramını açıklar.\nWYSIWYG editör kullanımını açıklar.',
      ['ÖĞRENME BİRİMİ 1: TEMEL KAVRAMLAR', '1.1. Web Sayfası Yayınlamada Temel Kavramlar', '1.1.1. Web Sayfası', '1.1.2. Web Sitesi', '1.1.3. Alan Adı (Domain)', '1.1.4. Alan Adı Uzantıları', '1.1.5. Alan Adı Alma İşlemi', '1.1.6. Hosting (Web Sitesi Barındırma)', '1.2. Web Yazılımcısı Rolleri', '1.3. İşaretleme Dili (HTML)']),
    r(8, 'Tasarım açısından içeriğin önemini açıklar.\nTasarımda yerleşim planının uygun olmasını sağlar.\nRenk düzeni, okunabilirlik, içerik-tasarım ilişkisini kurar.\nWeb sitesinin kullanıcı dostu olmasını ve erişim kolaylığını sağlar.\nWeb sitesinin tüm platformlarda sorunsuz çalışması ilkesini açıklar.',
      ['1.3.1. HTML Editörleri', '1.4. CSS [Cascaded Style Sheet (Basamaklı Stil Şablonu)]', '1.5. WYSIWYG [What You See Is What You Get]', 'Demokrasinin önemi', 'ÖĞRENME BİRİMİ 2: WEB TASARIM İLKELERİ', '2.1. İçerik', '2.2. Tasarım']),
    r(8, 'HTML5 belge yapısını kullanarak basit bir web sayfası hazırlar.',
      ['2.3. Biçimsellik', '2.3.1. Tipografi', '2.3.2. İçerik-Tasarım İlişkisi', '2.3.3. Renk Düzeni ve Okunabilirlik']),
    r(8, 'H1-H6 elemanlarını web sayfasında uygun şekilde kullanır.\nParagraflar ve metin biçimlendirme elemanlarını uygun şekilde web sayfasında kullanır.',
      ['2.4. İşlevsellik ve Kullanılabilirlik', '2.5. Güncellik', '2.6. Uygunluk ve Güvenilirlik', '2.7. Uyumluluk', '2.7.1. Tarayıcı Uyumluluğu', '2.7.2. Duyarlı (Responsive) Tasarım']),
    r(8, 'Paragraflar ve metin biçimlendirme elemanlarını uygun şekilde web sayfasında kullanır.',
      ['ÖĞRENME BİRİMİ 3: HTML5', '3.1. HTML5 Belge Yapısı', '3.1.1. HTML Hakkında']),
    r(8, 'Paragraflar ve metin biçimlendirme elemanlarını uygun şekilde web sayfasında kullanır.\nYerleşim (Layout) elemanlarını kullanarak örnek web uygulamaları geliştirir.',
      ['3.1.2. HTML5 Temel Etiketleri ve Belge Yapısı', '3.1.3. HTML5 Anlamsal Etiketler', '3.2. Başlık Elemanları', '3.2.1. HTML h1-h6 Başlık Etiketleri', '3.3. Paragraflar ve Metin Biçimlendirme', '3.3.1. p Etiketi', '3.3.2. b ve strong Etiketi', '3.3.3. i ve em Etiketleri', '3.3.9. Listeleme Etiketleri', '3.3.10. Tablolar', '3.4. Yerleşim Elemanları', '3.4.1. div Etiketi', '3.4.2. span Etiketi', '3.4.3. HTML5 Tasarım Şablonu']),
    r(8, 'Web sayfası içerisinde resim, ses/video gösteren HTML5 kodlarını uygular.\nWeb sayfaları arasında bağlantı sağlayan HTML kodunu uygular.',
      ['3.5. Medya (Resim, Video ve Ses) Elemanları', '3.5.1. HTML5 img Kullanımı', '3.5.2. HTML5 video Kullanımı', '3.5.3. HTML5 audio Kullanımı', '3.6. Bağlantı Elemanları', '3.6.1. HTML Bağlantı Söz Dizimi', '3.6.2. Sayfa İçi Bağlantılar', '3.6.3. Sayfalar Arası Bağlantılar']),
    r(8, 'Web sayfaları arasında bağlantı sağlayan HTML kodunu uygular.\nForm elemanlarının özelliklerini gösteren HTML5 kodunu uygular.',
      ['3.6.4. Site Dışına Bağlantı', '3.6.5. Diğer Bağlantı Çeşitleri', '3.7. Form Elemanları', '3.7.1. Formun Tanımı', '3.7.2. Form Oluşturmak', '3.7.3. Form Elemanları', '3.7.4. Veri Giriş (Input) Özellikleri', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(8, 'Stil uygulanacak olan elemanların seçimini yapar.',
      ['ÖĞRENME BİRİMİ 4: BASAMAKLI STİL ŞABLONU (CSS)', '4.1. CSS Ekleme Yöntemleri', '4.1.1. Satır İçi CSS Ekleme', '4.1.2. Sayfa İçi CSS Ekleme', '4.1.3. Sayfa Dışı (Haricî) CSS Ekleme', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(8, 'Stil uygulanacak olan elemanların seçimini yapar.\nKutu modeli özelliklerini açıklar.',
      ['4.1.4. Çok Kullanılan CSS Kodları', '4.1.5. Seçiciler (Selectors)', '4.2. Kutu Modeli Özellikleri ve Çalışma Prensipleri', '4.2.1. CSS Ölçü Birimleri', '4.2.2. Dış Boşluk (Margin)']),
    r(8, 'Kutu modeli özelliklerini açıklar.',
      ['4.2.3. Kenarlık (Border)', '4.2.4. İç Boşluk (Padding)', '4.2.5. İçerik (Content)', '4.2.6. Görünüm Ayarları', '4.2.7. Pozisyon Ayarları']),
    r(8, 'RGB değerleri ile renk tanımı yapar.',
      ['4.3. Renk Kullanımı ve Tipografi', '4.3.1. Klasik Renk Tanımlama Çeşitleri', '4.3.2. Geçişli Renk Tanımlama', '4.3.3. Tipografi']),
    r(8, 'Duyarlılık (Responsivity) kavramının önemini açıklar.',
      ['4.4. Duyarlılık (Responsivity)', '4.4.1. Medya Sorgusu', '4.4.2. Popüler CSS Frameworkleri', '4.4.3. Bootstrap Framework', '4.4.3.1. Konteyner Çeşitleri']),
    r(8, 'Değişkenler ve veri tiplerini kullanarak etkileşimli sayfalar geliştirir.',
      ['ÖĞRENME BİRİMİ 5: ETKİLEŞİM (JAVASCRİPT)', '5.1. Javascript Kod Yapısı ve Değişkenler', '5.1.1. Seçiciler', '5.1.2. Değişkenler ve Veri Tipleri', '5.1.3. Operatörlerin Kullanımı ve Kullanım Yerleri']),
    r(8, 'Fonksiyon türlerini kullanarak etkileşimli sayfa geliştirir.',
      ['5.2. Olaylar ve Fonksiyonlar', '5.2.1. Parametresiz (Basit) Fonksiyonlar', '5.2.2. Parametreli Fonksiyonlar', '5.2.3. Return Komutu']),
    r(8, 'Kontrol yapılarını kullanarak etkileşimli sayfa geliştirir.',
      ['5.3. Kontrol Yapıları', '5.3.1. if Yapısı', '5.3.2. if-else Yapısı', '5.3.3. else if Yapısı', '5.3.4. Switch-Case', '1.Dönem 2.Sınav']),
    r(8, 'Dizileri kullanarak etkileşimli sayfa geliştirir.\nDöngüleri kullanarak etkileşimli sayfa geliştirir.',
      ['5.4. Diziler', '5.5. Döngüler, Zamanlayıcılar ve Popüler Javascript Kütüphaneleri', '5.5.1. Sayaçlar', '5.5.2. For Döngüsü', '5.5.3. While Döngüsü', '5.5.4. Do-While Döngüsü']),
    r(8, 'Döngüleri kullanarak etkileşimli sayfa geliştirir.',
      ['5.5.5. Zamanlayıcılar', '5.5.6. Popüler Javascript Kütüphaneleri', '5.5.7. jQuery Kütüphanesi']),
    r(8, '.Net Core özelliklerini açıklar.',
      ['ÖĞRENME BİRİMİ 6: ARKA UÇ YAZILIM GELİŞTİRME', '6.1. .NET Core Teknolojisi', '6.1.1. .NET Kurulumu', '6.1.2. ASP.NET Core ve Diğer Teknolojilerden Farkı']),
    r(8, 'MVC tasarım desenini kullanarak web uygulamaları geliştirir.',
      ['6.2. MVC Tasarım Deseni', '6.2.1. MVC Projesi Oluşturma', '6.2.2. Model Katmanı']),
    r(8, 'MVC tasarım desenini kullanarak web uygulamaları geliştirir.',
      ['6.2.3. Controller Katmanı', '6.2.4. View Katmanı', '6.2.5. Razor Pages']),
    r(8, 'Standart klasör ve sayfaları kullanarak web uygulamaları geliştirir.\nAra katman (Middleware) yapısını kullanır.',
      ['6.3. Standart Klasör ve Dosyalar']),
    r(8, 'Ara katman (Middleware) yapısını kullanır.',
      ['6.4. Ara Katman (Middleware)', '6.4.1. İşlem Hattı (Pipeline)']),
    r(8, 'Yönlendirme (Routing) mekanizmasını kullanır.',
      ['6.4.2. İşlem Hattını Bölümleme', '6.4.3. Dâhilî Ara Katmanlar ve Öncelik Sıraları', '6.5. Yönlendirme (Routing)', '6.5.1. Varsayılan Yönlendirme', '6.5.2. Özel Yönlendirme Oluşturma', '6.5.3. Parametre Kısıtlamaları', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(8, 'Yönlendirme (Routing) mekanizmasını kullanır.',
      ['6.5.4. Öznitelik Yönlendirmeleri', '6.5.5. İstek Yolunu Değiştirme', '6.5.6. Belirteç Değiştirme']),
    r(8, 'Form işlemleri ve model doğrulama yapar.',
      ['6.6. Form İşlemleri', '6.6.1. Form GET Metodu Kullanımı', '6.6.2. Form POST Metodu Kullanımı', '2.Dönem 1.Sınav', '6.6.3. Form ile Dosya Yükleme']),
    r(8, 'Form işlemleri ve model doğrulama yapar.',
      ['6.6.4. Doğrulama İşlemleri (Validation)', '6.6.5. Model Doğrulama (Model Validation)', '6.6.6. İstemci Taraflı Doğrulama (Client Side Validation)']),
    r(8, 'Form işlemleri ve model doğrulama yapar.', ['']),
    r(8, 'Etiket yardımcılarını (Tag Helpers) kullanır.\nDoğrulama işlemleri yapar.',
      ['6.7. Etiket Yardımcıları (Tag Helper)', '6.7.1. Input Tag Helper Kullanımı', '6.7.2. Label Tag Helper Kullanımı', '6.7.3. Form Tag Helper Kullanımı', '6.7.4. Validation Tag Helper Kullanımı', 'Çocuk, insan sevgisi ve evrensellik']),
    r(8, 'Paket yöneticisini (NuGet) kullanır.\nEntity Framework Core ile veri tabanı işlemlerini yapar.',
      ['6.8. Paket Yöneticisi (NuGet)', '6.8.1. Paket Yöneticisi Araçları', '6.9. Entity Framework Core ile Veri Tabanı İşlemleri', '6.9.1. Entity Framework Core Kurulumu']),
    r(8, 'Entity Framework Core ile veri tabanı işlemlerini yapar.',
      ['6.9.2. Entity Framework Core DbContext Sınıfı', '6.9.3. Entity Framework Core DbSet Özelliği', '6.9.4. Entity Framework Core Migrations']),
    r(8, 'Entity Framework Core ile veri tabanı işlemlerini yapar.',
      ['6.9.5. Entity Framework Core Veri Ekleme', '6.9.6. Entity Framework Core Veri Alma ve LINQ Sorguları', '6.9.7. Entity Framework Core Veri Güncelleme']),
    r(8, 'Entity Framework Core ile veri tabanı işlemlerini yapar.',
      ['Atatürkçü düşüncede yer alan temel fikirler']),
    r(8, 'Entity Framework Core ile veri tabanı işlemlerini yapar.',
      ['6.9.8. Entity Framework Core Veri Silme', '6.9.9. Entity Framework Core Veri Tabanı İlişkileri']),
    r(8, 'Web servislerini kullanır.\nYayınlama (Publish) işlemini yapar.',
      ['6.10. Yayınlama (Publish) İşlemleri', '6.10.1. Çalışma Zamanına Bağlı Yayınlama', '6.10.2. Bağımsız Yayınlama', '2.Dönem 2.Sınav']),
    r(8, 'Web servislerini kullanır.\nYayınlama (Publish) işlemini yapar.',
      ['6.10.3. Windows ile IIS Sunucuda Yayınlama', '6.10.4. Web Servisler']),
    r(8, 'Web servislerini kullanır.\nYayınlama (Publish) işlemini yapar.',
      ['6.10.5. Web Servis Çeşitleri', '6.10.6. Web Servisler Katmanlı Mimari']),
    r(8, 'Web servislerini kullanır.\nYayınlama (Publish) işlemini yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== AÇIK KAYNAK İŞLETİM SİSTEMİ (Seçmeli) ====================
const acikKaynak = {
  name: 'Açık Kaynak İşletim Sistemi (Seçmeli)',
  area: AREA,
  gradeLevel: 'SEÇMELİ',
  courseName: 'Açık Kaynak İşletim Sistemi',
  weeklyHours: 2,
  defaultMethods: 'Anlatım, araştırma, gösteri, soru-cevap, uygulama, bireysel öğretim, beyin fırtınası',
  defaultTools: 'Akıllı tahta/projeksiyon, bilgisayar, yazıcı/tarayıcı, internet bağlantısı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(2, 'Açık kaynak kodlu işletim sisteminin temel kavramlarını açıklar.',
      ['ÖĞRENME BİRİMİ: AÇIK KAYNAK KODLU İŞLETİM SİSTEMİNİN KURULUMU VE TEMEL AYARLARI', '1.1. Açık Kaynak Kodlu İşletim Sistemi']),
    r(2, 'Açık kaynak kodlu işletim sisteminin kurulumunu yapar.',
      ['1.1.1. Açık ve Kapalı Kaynak İşletim Sistemleri Karşılaştırması', 'Demokrasinin önemi']),
    r(2, 'Açık kaynak kodlu işletim sisteminin kurulumunu yapar.',
      ['1.2. Açık Kaynak Kodlu İşletim Sistemi Kurulumu', '1.2.1. Sanallaştırma Yazılımı Kurulumu']),
    r(2, 'Açık kaynak kodlu işletim sisteminin kurulumunu yapar.\nAçık kaynak kodlu işletim sisteminin ağ ayarlarını yapar.',
      ['1.2.2. Sanallaştırma Yazılımı Ayarları', '1.2.3. Açık Kaynak İşletim Sistemi Kurulumu', '1.2.4. Kurulu İşletim Sistemi Yanına Açık Kaynak İşletim Sistemi Kurma']),
    r(2, '',
      ['1.2.5. Usb Belleğe Açık Kaynak İşletim Sistemi Kurma', '1.3. Açık Kaynak İşletim Sisteminde Ağ Ayarları', '1.3.1. Kablolu Ağ Ayarları']),
    r(2, '',
      ['1.3.2. Kablosuz Ağ Ayarları', '1.4. Masaüstü İşlemleri']),
    r(2, 'İşletim sistemi temel masaüstü işlemlerini yapar.',
      ['1.4.1. Arka Plan', '1.4.2. Aygıtlar']),
    r(2, 'İşletim sistemi temel masaüstü işlemlerini yapar.',
      ['1.4.3. Ekran Görüntüsü', '1.4.4. Gnu Görüntü İşleme Programı', 'Atatürk\'ün Cumhuriyetçilik İlkesi']),
    r(2, 'İşletim sistemi temel masaüstü işlemlerini yapar.',
      ['1.Dönem 1.Sınav', '1.4.5. İnce Ayarlar', '1.4.6. Uçbirim', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(2, 'Dosya yapısını ve dizin hiyerarşisini kullanır.\nAçık kaynak kodlu işletiminde program kurulumu ve güncellemeler yapar.',
      ['1.5. Açık Kaynak Kodlu İşletim Sisteminde Dosya ve Dizin İşlemleri']),
    r(2, '',
      ['1.5.1. Açık Kaynak İşletim Sisteminde Dosya Sistemi', '1.5.1.1. Linux Dosya Sistemi Hiyerarşisi']),
    r(2, '',
      ['1.5.1.2. Fsstnd\'ye Göre Kök Dizin Altındaki Temel Klasörler', 'ÖĞRENME BİRİMİ: AÇIK KAYNAK İŞLETİM SİSTEMİ YÖNETİMİ', '2.1. Paket Kurulumu ve Güncelleme İşlemleri']),
    r(2, 'Açık kaynak kodlu işletiminde program kurulumu ve güncellemeler yapar.',
      ['2.1.1. Pardus Mağazadan Program Kurma', '2.1.2. Komutla Paket Kurma', '2.1.3. Paket Yönetici ile Program Kurma']),
    r(2, '',
      ['2.2. Paket Güncelleme', '2.2.1. Grafik Arayüz ile Paket Güncelleme', '2.2.2. Komut Satırı Kullanılarak Paket Güncelleme']),
    r(2, 'Açık kaynak kodlu işletiminde program kurulumu ve güncellemeler yapar.',
      ['2.3. Paket Kaldırma', '2.3.1. Pardus Mağaza ile Paket Kaldırma', '2.3.2. Synaptic Paket Yönetici ile Paket Kaldırma', '2.3.3. Komut Satırı ile Paket Kaldırma']),
    r(2, 'Açık kaynak kodlu işletim sistemi kullanıcı ve grup işlemlerini yapar.',
      ['2.4. Kullanıcı ve Grup İşlemleri', '2.4.1. Kullanıcı (User) Hesabı', '2.4.2. Sistem Yöneticisi (Root)', '1.Dönem 2.Sınav']),
    r(2, 'Açık kaynak kodlu işletim sistemi kullanıcı ve grup işlemlerini yapar.',
      ['2.4.3. Kullanıcı Yönetimi', '2.4.3.1. Komut ile Kullanıcı Oluşturma']),
    r(2, '',
      ['2.4.3.2. Grafik Arayüz ile Kullanıcı Oluşturma', '2.4.4. Kullanıcı Silme']),
    r(2, 'Açık kaynak kodlu işletim sistemi kullanıcı ve grup işlemlerini yapar.',
      ['2.5. Grup Hesabı', '2.5.1. Grup Yönetimi', '2.5.1.1. Grup Ekleme', '2.5.1.2. Grup Silme']),
    r(2, 'Açık kaynak kodlu işletim sistemi kullanıcı ve grup işlemlerini yapar.',
      ['2.5.1.3. Grupların Görüntülenmesi', '2.5.1.4. Gruba Kullanıcı Ekleme ve Çıkarma', '2.5.1.5. Kullanıcı Gruplarını Sorgulama']),
    r(2, 'Açık kaynak kodlu işletim sistemi kullanıcı ve grup işlemlerini yapar.\nKelime işlemci editörü ile belgeler hazırlar.',
      ['2.6. Aktif / Pasif Hesap Ayarları', '2.7. Kimlik Değişimi']),
    r(2, 'Kelime işlemci editörü ile belgeler hazırlar.',
      ['ÖĞRENME BİRİMİ: AÇIK KAYNAK İŞLETİM SİSTEMİ TEMEL ARAÇLARI VE UYGULAMALARI', '3.1. LibreOffice', '3.1.1. Pardus Mağaza ile Kurulum', '3.1.2. Synaptic Paket Yöneticisi ile Kurulum', '3.1.3. İnternetten İndirilerek Kurulum', '3.2. LibreOffice Kelime İşlemci Editörü (Writer)', '3.2.1. Kelime İşlemci Arayüz Ekranı', '3.2.2. Kelime İşlemci Editörü ile Örnek Doküman Hazırlama']),
    r(2, 'Hesap tablosu yazılımı ile tablo ve çizelgeler hazırlar.',
      ['3.3. LibreOffice Hesap Tablosu Editörü (Calc)', '3.3.1. Hesap Tablosu Arayüzü', '3.3.2. Çalışma Sayfası ve Tablo Düzenleme', '3.3.3. Hesap Tablosunda İşlevler']),
    r(2, 'Sunum yazılımı ile sunumlar hazırlar.',
      ['3.4. LibreOffice Sunu Editörü (Impress)', '3.4.1. Sunu Editörü Arayüzü', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(2, 'Yardım ve bilgi alma komutlarını kullanır.',
      ['ÖĞRENME BİRİMİ: AÇIK KAYNAK KODLU İŞLETİM SİSTEMİNDE TEMEL KOMUT SATIRI İŞLEMLERİ', '4. Açık Kaynak Kodlu İşletim Sisteminde Temel Komut Satırı İşlemleri', '4.1. Yardım ve Bilgi Alma Komutları', '4.1.1. Help Komutu']),
    r(2, 'Yardım ve bilgi alma komutlarını kullanır.',
      ['4.1.2. Man (Manuel Pages) Komutu', '4.1.3. Whatis Komutu', '4.1.4. Apropos Komutu', '2.Dönem 1.Sınav', '4.1.5. Uname Komutu']),
    r(2, 'Yardım ve bilgi alma komutlarını kullanır.',
      ['4.1.6. Hostname Komutu', '4.1.7. lsb_release Komutu']),
    r(2, 'Yardım ve bilgi alma komutlarını kullanır.',
      ['4.1.8. Who-Whoami Komutu', '4.1.9. Zamansal Komutlar (Uptime, Date, Cal, Time)', '4.1.10. Which, Whereis ve Locate Komutları']),
    r(2, 'Yardım ve bilgi alma komutlarını kullanır.',
      ['4.1.11. Dmidecode Komutu', '4.1.12. Fdisk-l, Df, Du ve Free Komutları', '4.1.13. Stat ve Vmstat Komutu', 'Çocuk, insan sevgisi ve evrensellik']),
    r(2, 'Komut satırında dizin ve dosya işlemlerini yapar.',
      ['4.1.14. History Komutu', '4.2. Dosya ve Dizin İşlemleri', '4.2.1. Dosya ve Dizin İşlemleri Komutları (Pwd-Cd-ls-Mkdir)']),
    r(2, 'Komut satırında dizin ve dosya işlemlerini yapar.',
      ['4.2.1. Dosya ve Dizin İşlemleri Komutları (Tree-Touch-Rm-Rmdir, Cat-Tac-Rev-Echo)']),
    r(2, 'Komut satırında dizin ve dosya işlemlerini yapar.',
      ['4.2.1. Dosya ve Dizin İşlemleri Komutları (More-Less-Head-Tail, Nl-Sort-Paste)']),
    r(2, 'Komut satırında dizin ve dosya işlemlerini yapar.',
      ['4.2.1. Dosya ve Dizin İşlemleri Komutları (Tee-Tr-Diff-Cmp, Wc-Cut-Grep-Find, Xargs-Cp-Mv-Shred)', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(2, 'Dosya arşiv komutlarını kullanır.',
      ['4.3. Arşiv İşlemleri', '4.3.1. Tar Komutu', '4.3.2. Gzip-Gunzip ve Bzip2-Bunzip2 Komutları']),
    r(2, 'Dosya arşiv komutlarını kullanır.',
      ['4.3.3. Zcat-Zgrep ve Bzcat-Bzgrep Komutları', '4.3.4. Zip-Unzip Komutları', '4.3.5. Rar-Unrar Komutları', '2.Dönem 2.Sınav']),
    r(2, 'Erişim yetki komutlarını kullanarak düzenlemeler yapar.',
      ['4.4. Yetkilendirme İşlemleri', '4.4.1. Chmod Komutu']),
    r(2, 'Erişim yetki komutlarını kullanarak düzenlemeler yapar.',
      ['4.4.2. Chown ve Chgrp Komutları', '4.4.3. Chattr ve Lsattr Komutları']),
    r(2, 'Erişim yetki komutlarını kullanarak düzenlemeler yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== SOSYAL MEDYA (Seçmeli) ====================
const sosyalMedya = {
  name: 'Sosyal Medya (Seçmeli)',
  area: AREA,
  gradeLevel: 'SEÇMELİ',
  courseName: 'Sosyal Medya',
  weeklyHours: 2,
  defaultMethods: 'Anlatım, araştırma, gösteri, örnek olay, soru-cevap, uygulama, bireysel öğretim, beyin fırtınası',
  defaultTools: 'Akıllı tahta/projeksiyon, bilgisayar, yazıcı/tarayıcı, internet bağlantısı',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(2, 'E-ticarete ilişkin temel kavramları açıklar.',
      ['1. E-TİCARET', '1.1. E-TİCARETE İLİŞKİN TEMEL KAVRAMLAR', '1.1.1. Ticaret', 'Demokrasinin önemi']),
    r(2, 'E-ticarete ilişkin temel kavramları açıklar.',
      ['1.1.2. E-Ticaret', '1.1.3. E-Ticaretin Avantajları ve Dezavantajları', '1.2. E-TİCARET TÜRLERİ']),
    r(2, 'E-ticaret türlerini açıklar.',
      ['1.2.4. E-Ticaretin Çalışması', '1.3. E-TİCARETTE PAZARLAMA AŞAMALARI', '1.3.5. E-Ticaret İş Planlaması']),
    r(2, 'E-ticarette pazarlama aşamalarını sıralar.',
      ['1.3.5.1. E-Ticaret İş Planı', '1.3.5.2. Neden İş Planı Yapılmalıdır?', '1.3.5.3. E-Ticaret İş Planının Farkları', '1.3.5.4. E-Ticaret İş Planı Nasıl Yapılır?']),
    r(2, '',
      ['1.3.6. E-Ticarette Pazarlama İçin Kullanılacak Araçlar', '1.3.7. Elektronik Pazarlama Yöntemleri', '1.4. E-TİCARETTE ALTYAPI VE GÜVENLİK']),
    r(2, 'E-ticarette pazarlama aşamalarını sıralar.',
      ['1.4.1. E-Ticaret Sitelerinde Altyapı', '1.4.1.1. E-Ticaret Altyapı Bileşenleri', '1.4.1.2. E-Ticaret Altyapı Seçimi']),
    r(2, 'E-ticaret için gereken teknik alt yapı ve güvenlik unsurlarını açıklar.',
      ['1.4.1.3. E-Ticaret Hazır Yazılım Paketleri', '1.4.2. E-Ticarette Güvenlik', '1.4.2.1. E-Ticarette Karşılaşılan Güvenlik Tehditleri', '1.4.2.2. Güvenlik Tehditlerine Karşı Alınacak Önlemler']),
    r(2, 'E-ticaret için gereken teknik alt yapı ve güvenlik unsurlarını açıklar.',
      ['Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav', '1.4.2.3. Site İçi Güvenliği Sağlama']),
    r(2, 'E-ticaret ile ilgili hukuki düzenlemeleri takip eder.',
      ['1.4.3. E-Ticarette Kullanılan Ödeme Yöntemleri', '1.5. E-TİCARETTE HUKUKİ DÜZENLEMELER', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(2, 'Sosyal medyayı kullanırken temel hak ve özgürlükler kapsamında etik kurallara uygun paylaşım yapar.',
      ['2. SOSYAL MEDYA', '2.1. ETİK VE BİLİŞİM ETİĞİ']),
    r(2, 'Sosyal medyayı kullanırken temel hak ve özgürlükler kapsamında etik kurallara uygun paylaşım yapar.',
      ['2.1.1. Bilişim Temel Hak ve Özgürlükleri', '2.1.2. Sosyal Medya Etiği', '2.1.3. İnternet Etiği']),
    r(2, 'Sosyal medyayı kullanırken temel hak ve özgürlükler kapsamında etik kurallara uygun paylaşım yapar.', ['']),
    r(2, 'Kimlik gizlemeden hukuki kuralların sorumluluklarını göze alarak sosyal medya kullanır.',
      ['2.2. BİLGİ GÜVENLİĞİ VE HUKUKİ KURALLAR', '2.2.1. Bilgi ve Bilgi Güvenliği']),
    r(2, 'Sosyal medya kullanırken siber şiddete karşı kendini korur.',
      ['2.3. SİBER ZORBALIK', '2.3.1. Güvenlik Yazılımları']),
    r(2, 'Sosyal medya kullanırken siber şiddete karşı kendini korur.',
      ['2.3.2. Siber Zorbalıktan Korunma Yöntemleri']),
    r(2, 'Dijital marka yönetimini ve dijital dönüşüm gerekliliğini açıklar.\nSosyal medya araçlarını açıklar.',
      ['2.4. DİJİTAL MARKA YÖNETİMİ VE DİJİTAL DÖNÜŞÜM', '1.Dönem 2.Sınav']),
    r(2, '',
      ['2.5. SOSYAL MEDYA ARAÇLARI', '2.5.1. Sosyal Medya Platformu Yardımcı Araçları']),
    r(2, 'Sosyal medya araçlarını açıklar.',
      ['2.5.1. Sosyal Medya Platformu Yardımcı Araçları']),
    r(2, 'Sosyal medya platformları için içerik planı oluşturur.',
      ['2.6. SOSYAL MEDYA PLATFORMLARI İÇİN İÇERİK PLANI OLUŞTURMA', '2.6.1. Hedef Kitlenin Tespiti']),
    r(2, 'Sosyal medya platformları için içerik planı oluşturur.',
      ['2.6.2. Uygun Kategorilerin Oluşturulması']),
    r(2, 'Sosyal medya platformları için içerik planı oluşturur.',
      ['2.6.3. İçerik Planı Takviminin Hazırlanması']),
    r(2, 'Sosyal medya analizi ve raporlama yapar.',
      ['2.7. SOSYAL MEDYA ANALİZİ VE RAPORLAMA', '2.7.1. Hedef Kitle ile İletişim']),
    r(2, 'Sosyal medya analizi ve raporlama yapar.',
      ['2.7.2. Sosyal Medya Analizi']),
    r(2, 'Sosyal medyada kriz iletişimi kampanyası planlama ve uygulama yapar.',
      ['2.8. SOSYAL MEDYADA KRİZ İLETİŞİMİ', '2.8.1. Örnek Olay', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(2, 'Veri ve bilgi kavramını açıklar.',
      ['3. VERİ ANALİZİ VE GRAFİKLER', '3.1. VERİ, ENFORMASYON VE BİLGİ']),
    r(2, 'Veri türlerini ve çevresindeki veri kaynaklarını açıklar.\nVeri toplama araçlarıyla veriyi toplar ve veri kümesi oluşturur.',
      ['3.2. VERİ TÜRLERİ', '2.Dönem 1.Sınav', '3.3. VERİ TOPLAMA', '3.3.1. Veri Toplama Yöntemleri']),
    r(2, '', ['']),
    r(2, 'Veri toplama araçlarıyla veriyi toplar ve veri kümesi oluşturur.',
      ['3.3.2. Veri Kaynakları', '3.3.3. Veri Kümesi Oluşturma', '3.4. VERİ HAZIRLAMA']),
    r(2, 'Tablolar halinde veri hazırlar.',
      ['Çocuk, insan sevgisi ve evrensellik']),
    r(2, 'Grafik çeşitlerini tanır ve amaca uygun grafik seçimi yapar.',
      ['3.5. GRAFİK ÇEŞİTLERİ', '3.5.1. Sütun ve Çubuk Grafikler', '3.5.2. Çizgi Grafikler', '3.5.3. Pasta ve Halka Grafikler']),
    r(2, '',
      ['3.5.4. Alan Grafikleri', '3.5.5. XY (Dağılım) ve Kabarcık Grafikleri', '3.5.6. Hisse Senedi Grafiği']),
    r(2, 'Grafik çeşitlerini tanır ve amaca uygun grafik seçimi yapar.',
      ['3.5.7. Radar Grafikleri', '3.5.8. Ağaç Haritası Grafiği', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(2, 'Grafik çeşitlerini tanır ve amaca uygun grafik seçimi yapar.', ['']),
    r(2, 'Grafik çeşitlerini tanır ve amaca uygun grafik seçimi yapar.',
      ['3.5.9. Güneş Işığı Grafiği', '3.5.10. Histogram Grafikleri', '3.5.11. Kutu ve Yatay Çizgi Grafiği']),
    r(2, 'Grafik çeşitlerini tanır ve amaca uygun grafik seçimi yapar.',
      ['3.5.12. Şelale Grafikleri', '3.5.13. Huni Grafiği', '3.5.14. Bileşik Grafikler', '2.Dönem 2.Sınav']),
    r(2, 'Veri görselleştirme araçlarını kullanarak veriye dayalı grafikler oluşturur.',
      ['3.6. GRAFİK OLUŞTURMA']),
    r(2, 'Veri görselleştirme araçlarını kullanarak veriye dayalı grafikler oluşturur.',
      ['3.6. GRAFİK OLUŞTURMA']),
    r(2, 'Veri görselleştirme araçlarını kullanarak veriye dayalı grafikler oluşturur.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

// ==================== ROBOTİK VE KODLAMA (10. Sınıf) ====================
const robotik = {
  name: '10. Sınıf Robotik ve Kodlama',
  area: AREA,
  gradeLevel: '10.SINIF',
  courseName: 'Robotik ve Kodlama',
  weeklyHours: 3,
  defaultMethods: 'Anlatım, gösterip yaptırma, soru cevap, grup çalışması, beyin fırtınası, uygulama',
  defaultTools: 'Mikrodenetleyici kart, devre elemanları, sensörler, motorlar, piller, breadboard',
  signTeachers: SIGN,
  principalName: PRINCIPAL,
  rows: [
    r(3, 'Mikrodenetleyici kart yapısı ve çeşitlerini açıklar.',
      ['ÖĞRENME BİRİMİ: ROBOTİK İÇİN MİKRODENETLEYİCİ KART', '1. Mikrodenetleyici Kart Yapısı ve Çeşitleri', '1.1. Mikrodenetleyici kartın fiziksel yapısı', '1.2. Mikrodenetleyici kart çeşitleri']),
    r(3, 'Robot türleri ve eğitsel amaçlı robotları açıklar.',
      ['1.3. Online çizim ve simülasyon programına giriş', '1.4. Online çizim ve simülasyon programının menüleri', '1.5. Online çizim ve simülasyon programında Blink uygulaması', 'Demokrasinin önemi']),
    r(3, 'Robotta mekanik/elektromekanik bileşenleri açıklar.\nRobotta elektronik bileşenleri açıklar.',
      ['2. Robot Türleri ve Eğitsel Amaçlı Robotlar', '2.1. Robot kavramı', '2.2. Robot çeşitleri']),
    r(3, 'Sistem gereksinimlerine uygun mikrodenetleyici kart yazılımı kurulumunu yapar.',
      ['2.3. Eğitsel robotlar', '2.4. Online çizim ve simülasyon programında düğme (button) uygulaması', '3. Robotta Mekanik/Elektromekanik Bileşenler', '3.1. Online çizim ve simülasyon programında LED uygulamaları', '4. Robotta Elektronik Bileşenler']),
    r(3, 'Bilgisayarla mikrodenetleyici kart arasında uygun yöntemlerle bağlantı oluşturur.',
      ['ÖĞRENME BİRİMİ: MİKRODENETLEYİCİ KART UYGULAMALARI', '1. Sistem Gereksinimlerine Uygun Mikrodenetleyici Kart', '1.1. Mikrodenetleyici kart yazılımı']),
    r(3, 'Geliştirme ortamı söz dizimi kurallarını programa uygun şekilde kullanır.',
      ['1.2. Mikrodenetleyici kart yazılımı kurulumu', '2. Mikrodenetleyici Kartın Bilgisayarla Bağlantısının Gerçekleştirilmesi', '2.1. Bilgisayar ile mikrodenetleyici arasında bağlantı oluşturmak için gerekli adımlar']),
    r(3, 'Geliştirme ortamı söz dizimi kurallarını programa uygun şekilde kullanır.',
      ['2.2. Blink örnek uygulamasının program kodları', '2.3. Mikrodenetleyici kart çeşitlerini ve bağlantı portunun seçimi', '2.4. Mikrodenetleyici karta programın yüklenmesi']),
    r(3, '',
      ['3. Geliştirme Ortamının Kullanılması', '3.1. LED\'in yapısı', '3.2. Breadboard kullanımı', '3.3. Mikrodenetleyici IDE programında söz dizim kuralları', '3.4. Mikrodenetleyici kart ve Breadboard\'a gerekli devre elemanlarının takılması', '3.5. Mikrodenetleyici kart ile 1 LED\'li uygulama', '3.6. Mikrodenetleyici kart ile 2, 5 ve 7 LED\'li uygulamalar', '3.7. Mikrodenetleyici kart ile trafik lambası kontrolü uygulaması', 'Atatürk\'ün Cumhuriyetçilik İlkesi', '1.Dönem 1.Sınav']),
    r(3, 'Geliştirme ortamı söz dizimi kurallarını programa uygun şekilde kullanır.',
      ['3.8. Mikrodenetleyici kartın dijital portlarının kullanımı', '3.9. Anahtar kullanımı ve çeşitleri', '3.10. Anahtar ile dijital giriş uygulamaları', 'Atatürk\'ün eğitime ve bilime verdiği önem']),
    r(3, 'Geliştirme ortamı söz dizimi kurallarını programa uygun şekilde kullanır.',
      ['3.11. Buton kullanımı ve çeşitleri', '3.12. Buton ile dijital giriş uygulamaları']),
    r(3, 'Seri iletişim yöntemlerini geliştirilen programa uygun şekilde kullanır.',
      ['4. Seri İletişim Yöntemleri', '4.1. Seri port ekranı', '4.2. Serial Port bağlantı hatası ve çözümü', '4.3. Serial portta örnek uygulama']),
    r(3, 'Operatörleri geliştirilen programa uygun şekilde kullanır.',
      ['5. Geliştirme Ortamında Operatörlerin Kullanılması', '5.1. Geliştirme ortamında operatörlerin kullanımı', '5.2. Potansiyometre ile analog giriş uygulaması']),
    r(3, 'Operatörleri geliştirilen programa uygun şekilde kullanır.',
      ['5.3. Potansiyometre ile LED\'lerin yanma hızını ayarlama']),
    r(3, 'Operatörleri geliştirilen programa uygun şekilde kullanır.\nDeğişkenleri geliştirilen programa uygun şekilde kullanır.',
      ['5.4. LDR ile ışık seviyesinin ölçümü']),
    r(3, '',
      ['5.5. Analog çıkış (PWM)', '5.6. LED parlaklığı ayarlayan uygulama', '5.7. RGB LED']),
    r(3, '',
      ['5.8. Mikrodenetleyici kart ile RGB LED uygulaması', '1.Dönem 2.Sınav', '5.9. Buzzer elamanı ve çeşitleri', '5.10. Mikrodenetleyici kart ile Buzzer uygulamaları']),
    r(3, '', ['']),
    r(3, '',
      ['6. Geliştirme Ortamında Değişkenlerin Kullanılması', '6.1. Geliştirme ortamında değişkenlerin kullanımı', '6.2. Dizilerin kullanımı']),
    r(3, 'Değişkenleri geliştirilen programa uygun şekilde kullanır.\nFonksiyonları geliştirilen programa uygun şekilde kullanır.',
      ['6.3. Çok boyutlu diziler (matrisler)', '6.4. Dizi uygulamaları']),
    r(3, '',
      ['7. Geliştirme Ortamında Fonksiyonların Kullanılması', '7.1. Geliştirme ortamında fonksiyonların kullanımı', '7.2. 7 Segment display devre elamanı', '7.3. Mikrodenetleyici Kart İle 7 Segment Display uygulamaları']),
    r(3, 'Ortam kütüphanelerini geliştirilen programa uygun şekilde kullanır.',
      ['8. Ortam Kütüphaneleri', '8.1. Ortam kütüphanelerine erişim', '8.2. Uzaktan Kumanda İle RGB LED Uygulamaları', '8.3. Mikrodenetleyici IDE programında IRremote kütüphanesi kullanımı', '8.4. Uzaktan Kumanda İle 7 Segment Display Uygulaması']),
    r(3, 'Ortam kütüphanelerini geliştirilen programa uygun şekilde kullanır.',
      ['8.5. Ultrasonik mesafe sensörü ve çalışma prensibi', '8.6. Ultrasonik mesafe sensörü uygulamaları']),
    r(3, '',
      ['8.7. LCD ekran elemanının kullanımı', '8.8. LCD ekran uygulaması']),
    r(3, '',
      ['8.9. LCD ile sıcaklık sensörü uygulaması', 'Atatürk\'ün vatan ve millet sevgisi']),
    r(3, 'Bireysel veya toplumsal soruna çözüm üreten özgün bir proje geliştirir.',
      ['ÖĞRENME BİRİMİ: ROBOT UYGULAMALARI', '1. Özgün Proje Çalışması', '1.1. Eğitsel robot bileşenleri', '1.2. Robot gövdesi', '1.3. Motorlar']),
    r(3, 'Bireysel veya toplumsal soruna çözüm üreten özgün bir proje geliştirir.',
      ['1.4. Tekerlekler', '1.5. Motor Sürücüleri', '2.Dönem 1.Sınav', '1.6. Mesafe sensörü', '1.7. Çizgi izleme sensörü']),
    r(3, '',
      ['1.8. IR alıcıları', '1.9. Enerji kaynağı']),
    r(3, '',
      ['1.10. Eğitsel robotun devre şeması', '1.11. Eğitsel robotun montajı', 'Çocuk, insan sevgisi ve evrensellik']),
    r(3, '', ['']),
    r(3, 'Bireysel veya toplumsal soruna çözüm üreten özgün bir proje geliştirir.',
      ['1.12. Eğitsel robotun programlanması']),
    r(3, 'Proje sunumu yapar.',
      ['2. Projenin Sunumu', '2.1. Eğitsel robotun uzaktan kumanda ile kontrolü', '2.2. Uygulamanın çalıştırılması ve sunumu', '2.3. Eğitsel robot ile engelden kaçma uygulaması', 'Atatürkçü düşüncede yer alan temel fikirler']),
    r(3, '', ['']),
    r(3, '', ['']),
    r(3, 'Proje sunumu yapar.',
      ['2.4. Engelden kaçan robotun çalıştırılması ve sunumu']),
    r(3, 'Proje sunumu yapar.',
      ['2.5. Eğitsel robot ile çizgi izleme uygulaması', '2.6. Çizgi izleyen robotun çalıştırılması ve sunumu', '2.Dönem 2.Sınav']),
    r(3, 'Proje sunumu yapar.',
      ['2.7. Eğitsel robotun Bluetooth ile kontrolü uygulaması']),
    r(3, 'Proje sunumu yapar.',
      ['2.8. Uygulamanın çalıştırılması ve sunumu']),
    r(3, 'Proje sunumu yapar.',
      ['Dönem Sonu Faaliyet Haftası Etkinlikleri'])
  ]
};

module.exports = [programlamaTemelleri, bilisimTemelleri, nesneTabanli, webProgramciligi, webTabanli, acikKaynak, sosyalMedya, robotik];
